CREATE TABLE [dbo].[FormEmployment] (
    [Id] BIGINT IDENTITY (1, 1) NOT NULL,
    [AccountId] BIGINT NULL,
    [FirstName] NVARCHAR (1000) NULL,
    [MiddleName] NVARCHAR (1000) NULL,
    [LastName] NVARCHAR (1000) NULL,
    [OtherNamesYes]  BIT NULL,
    [OtherNamesNo]  BIT NULL,
    [DaytimePhone] NVARCHAR (1000) NULL,
    [EmailAddress] NVARCHAR (1000) NULL,
    [CityOfBirth] NVARCHAR (1000) NULL,
    [ProvinceStateOfBirth] NVARCHAR (1000) NULL,
    [CountryOfBirth] NVARCHAR (1000) NULL,
    [ForInitial]  BIT NULL,
    [ForReplacement]  BIT NULL,
    [ForRenewal]  BIT NULL,
    [MailingStreetAddressApt]  BIT NULL,
    [MailingStreetAddressSte]  BIT NULL,
    [MailingStreetAddressFlr]  BIT NULL,
    [MailingStreetAddressYes]  BIT NULL,
    [MailingStreetAddressText] NVARCHAR (1000) NULL,
    [CityOrTown] NVARCHAR (1000) NULL,
    [State] NVARCHAR (1000) NULL,
    [Province] NVARCHAR (1000) NULL,
    [ZipCode] NVARCHAR (1000) NULL,
    [DifferentPhysicalYes] BIT NULL,
    [DifferentPhysicalNo] BIT NULL,
    [GenderMale]  BIT NULL,
    [GenderFemale]  BIT NULL,
    [DateOfBirth] DATETIME2 (7)   NULL,
    [ContactCityOfBirth] NVARCHAR (1000) NULL,
    [ProvinceOrStateOfBirth] NVARCHAR (1000) NULL,
    [ContactCountryOfBirth] NVARCHAR (1000) NULL,
    [MaritalStatusSingle] BIT NULL,
    [MaritalStatusMarried] BIT NULL,
    [MaritalStatusDivorced] BIT NULL,
    [MaritalStatusWidowed] BIT NULL, 
    [AlienRegistrationNumber] NVARCHAR (1000) NULL,
    [FormI765Yes] BIT NULL,
    [FormI765No] BIT NULL,
    [SocialSecurityYes] BIT NULL,
    [SocialSecurityNo] BIT NULL,
    [SSAYes] BIT NULL,
    [SSANo] BIT NULL,
    [DisclosureYes] BIT NULL,
    [DisclosureNo] BIT NULL,
    [FatherFirstName] NVARCHAR (1000) NULL,
    [FatherLastName] NVARCHAR (1000) NULL,
    [MotherFirstName] NVARCHAR (1000) NULL,
    [MotherLastName] NVARCHAR (1000) NULL,
    [1Country] NVARCHAR (1000) NULL,
    [2Country] NVARCHAR (1000) NULL,
    [3Country] NVARCHAR (1000) NULL,
    [ArrivalDeparture] NVARCHAR (1000) NULL,
    [DateAuthorized] NVARCHAR (1000) NULL,
    [PassportNumber] NVARCHAR (1000) NULL,
    [TravelDocumentNumber] NVARCHAR (1000) NULL,
    [CountryIssuance] NVARCHAR (1000) NULL,
    [DateLastArrival] DATETIME2 (7)   NULL,
    [PlaceLastArrival] NVARCHAR (1000) NULL,
    [StatusLastArrival] NVARCHAR (1000) NULL,
    [StatusCategory] NVARCHAR (1000) NULL,
    [SudentExchangeVisitor] NVARCHAR (1000) NULL, 
    [EligibilityCategory] NVARCHAR (1000) NULL,
    [Degree] NVARCHAR (1000) NULL,
    [EmployerName] NVARCHAR (1000) NULL,
    [CompanyIdentification] NVARCHAR (1000) NULL,
    [ReceiptNumber] NVARCHAR (1000) NULL,
    [Arrested1Yes]  BIT NULL,
    [Arrested1No]  BIT NULL,
    [LawfullyYes]  BIT NULL,
    [LawfullyNo]  BIT NULL,
    [SecretaryYes]  BIT NULL,
    [SecretaryNo]  BIT NULL,
    [Notice1]  NVARCHAR (1000) NULL,
    [Arrested2Yes]  BIT NULL,
    [Arrested2No]  BIT NULL,
    [Notice2]  NVARCHAR (1000) NULL,
    [InterpreterFirstName] NVARCHAR (1000) NULL,
    [InterpreterLastName] NVARCHAR (1000) NULL,
    [InterpreterBusinessName]  NVARCHAR (1000) NULL,
    [InterpreterMailingStreetAddressApt] BIT NULL,
    [InterpreterMailingStreetAddressSte] BIT NULL,
    [InterpreterMailingStreetAddressFlr] BIT NULL,
    [InterpreterMailingStreetAddressNumber] BIT NULL,
    [InterpreterMailingStreetAddressText] NVARCHAR (1000) NULL,
    [InterpreterCityOrTown] NVARCHAR (1000) NULL,
    [InterpreterProvince] NVARCHAR (1000) NULL,
    [InterpreterZipCode]  NVARCHAR (1000) NULL,
    [InterpreterCountry]  NVARCHAR (1000) NULL,
    [InterpreterDaytimeTelephoneNumber]  NVARCHAR (1000) NULL,
    [InterpreterEmail]  NVARCHAR (1000) NULL,
    [Deleted] BIT CONSTRAINT [DF_FormEmployment_Deleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_FormEmployment] PRIMARY KEY CLUSTERED ([Id] ASC)
);
