CREATE TABLE [dbo].[FormEmployment] (
    [Id]                               BIGINT          IDENTITY (1, 1) NOT NULL,
    
    [EmploymentNameFirstName] NVARCHAR (1000) NULL,
    [EmploymentNameMiddleName] NVARCHAR (1000) NULL,
    [EmploymentNameLastName] NVARCHAR (1000) NULL,
    [EmploymentNameOtherNamesYes]  BIT NULL,
    [EmploymentNameOtherNamesNo]  BIT NULL,
    [EmploymentNameDaytimePhone] NVARCHAR (1000) NULL,
    [EmploymentNameEmailAddress] NVARCHAR (1000) NULL,
    [EmploymentNameCityOfBirth] NVARCHAR (1000) NULL,
    [EmploymentNameProvinceStateOfBirth] NVARCHAR (1000) NULL,
    [EmploymentNameCountryOfBirth] NVARCHAR (1000) NULL,
    [EmploymentNameAppyingForInitial]  BIT NULL,
    [EmploymentNameAppyingForReplacement]  BIT NULL,
    [EmploymentNameAppyingForRenewal]  BIT NULL,
    [EmploymentAddressMailingStreetAddressApt]  BIT NULL,
    [EmploymentAddressMailingStreetAddressSte]  BIT NULL,
    [EmploymentAddressMailingStreetAddressFlr]  BIT NULL,
    [EmploymentAddressMailingStreetAddressYes]  BIT NULL,
    [EmploymentAddressMailingStreetAddressText] NVARCHAR (1000) NULL,
    [EmploymentAddressCityOrTown] NVARCHAR (1000) NULL,
    [EmploymentAddressState] NVARCHAR (1000) NULL,
    [EmploymentAddressProvince] NVARCHAR (1000) NULL,
    [EmploymentAddressZipCode] NVARCHAR (1000) NULL,
    [EmploymentAddressDifferentPhysicalYes] BIT NULL,
    [EmploymentAddressDifferentPhysicalNo] BIT NULL,
    [EmploymentContactGenderMale]  BIT NULL,
    [EmploymentContactGenderFemale]  BIT NULL,
    [EmploymentContactDateOfBirth] DATETIME2 (7)   NULL,
    [EmploymentContactCityOfBirth] NVARCHAR (1000) NULL,
    [EmploymentContactProvinceOrStateOfBirth] NVARCHAR (1000) NULL,
    [EmploymentContactCountryOfBirth] NVARCHAR (1000) NULL,
    [EmploymentContactMaritalStatusSingle] BIT NULL,
    [EmploymentContactMaritalStatusMarried] BIT NULL,
    [EmploymentContactMaritalStatusDivorced] BIT NULL,
    [EmploymentContactMaritalStatusWidowed] BIT NULL, 
    [EmploymentContactAlienRegistrationNumber] NVARCHAR (1000) NULL,
    [EmploymentContactFormI765Yes] BIT NULL,
    [EmploymentContactFormI765No] BIT NULL,
    [EmploymentContactSocialSecurityYes] BIT NULL,
    [EmploymentContactSocialSecurityNo] BIT NULL,
    [EmploymentContactSSAYes] BIT NULL,
    [EmploymentContactSSANo] BIT NULL,
    [EmploymentContactConsentDisclosureYes] BIT NULL,
    [EmploymentContactConsentDisclosureNo] BIT NULL,
    [EmploymentParentFatherFirstName] NVARCHAR (1000) NULL,
    [EmploymentParentFatherLastName] NVARCHAR (1000) NULL,
    [EmploymentParentMotherFirstName] NVARCHAR (1000) NULL,
    [EmploymentParentMotherLastName] NVARCHAR (1000) NULL,
    [EmploymentParent1Country] NVARCHAR (1000) NULL,
    [EmploymentParent2Country] NVARCHAR (1000) NULL,
    [EmploymentParent3Country] NVARCHAR (1000) NULL,
    [EmploymentParentArrivalDeparture] NVARCHAR (1000) NULL,
    [EmploymentParentDateAuthorized] NVARCHAR (1000) NULL,
    [EmploymentParentPassportNumber] NVARCHAR (1000) NULL,
    [EmploymentParentTravelDocumentNumber] NVARCHAR (1000) NULL,
    [EmploymentParentCountryIssuance] NVARCHAR (1000) NULL,
    [EmploymentParentDateLastArrival] DATETIME2 (7)   NULL,
    [EmploymentParentPlaceLastArrival] NVARCHAR (1000) NULL,
    [EmploymentParentImmigrationStatusLastArrival] NVARCHAR (1000) NULL,
    [EmploymentParentImmigrationStatusCategory] NVARCHAR (1000) NULL,
    [EmploymentParentSudentExchangeVisitor] NVARCHAR (1000) NULL, 
    [EmploymentAuthorizationEligibilityCategory] NVARCHAR (1000) NULL,
    [EmploymentAuthorizationDegree] NVARCHAR (1000) NULL,
    [EmploymentAuthorizationEmployerName] NVARCHAR (1000) NULL,
    [EmploymentAuthorizationCompanyIdentification] NVARCHAR (1000) NULL,
    [EmploymentAuthorizationReceiptNumber] NVARCHAR (1000) NULL,
    [EmploymentAuthorization1ArrestedYes]  BIT NULL,
    [EmploymentAuthorization1ArrestedNo]  BIT NULL,
    [EmploymentAuthorizationLawfullyYes]  BIT NULL,
    [EmploymentAuthorizationLawfullyNo]  BIT NULL,
    [EmploymentAuthorizationSecretaryYes]  BIT NULL,
    [EmploymentAuthorizationSecretaryNo]  BIT NULL,
    [EmploymentAuthorization1NoticeYes]  BIT NULL,
    [EmploymentAuthorization1NoticeNo]  BIT NULL,
    [EmploymentAuthorization2ArrestedYes]  BIT NULL,
    [EmploymentAuthorization2ArrestedNo]  BIT NULL,
    [EmploymentAuthorization2NoticeYes]  BIT NULL,
    [EmploymentAuthorization2NoticeNo]  BIT NULL,
    [EmploymentInterpreterFirstName] NVARCHAR (1000) NULL,
    [EmploymentInterpreterLastName] NVARCHAR (1000) NULL,
    [EmploymentInterpreterBusinessName]  NVARCHAR (1000) NULL,
    [EmploymentInterpreterMailingStreetAddressApt] BIT NULL,
    [EmploymentInterpreterMailingStreetAddressSte] BIT NULL,
    [EmploymentInterpreterMailingStreetAddressFlr] BIT NULL,
    [EmploymentInterpreterMailingStreetAddressNumber] BIT NULL,
    [EmploymentInterpreterMailingStreetAddressText] NVARCHAR (1000) NULL,
    [EmploymentInterpreterCityOrTown] NVARCHAR (1000) NULL,
    [EmploymentInterpreterProvince] NVARCHAR (1000) NULL,
    [EmploymentInterpreterZipCode]  NVARCHAR (1000) NULL,
    [EmploymentInterpreterCountry]  NVARCHAR (1000) NULL,
    [EmploymentInterpreterDaytimeTelephoneNumber]  NVARCHAR (1000) NULL,
    [EmploymentInterpreterEmail  NVARCHAR (1000) NULL,
    
    [Deleted]                          BIT             CONSTRAINT [DF_FormEmployment_Deleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_FormEmployment] PRIMARY KEY CLUSTERED ([Id] ASC)
);

