CREATE TABLE [dbo].[FormVisaSpouse] (
    	[Id] BIGINT IDENTITY (1, 1) NOT NULL,
    	[AccountId] BIGINT NULL,
	[SponsorNameFirstName]              NVARCHAR (1000) NULL,
	[SponsorNameMiddleName]              NVARCHAR (1000) NULL,
	[SponsorNameDoesNotApply]      BIT             NULL,
	[SponsorNameLastName]              NVARCHAR (1000) NULL,
	[SponsorNameDaytimePhoneNumber]              NVARCHAR (1000) NULL,
	[SponsorNameGenderMale]      BIT             NULL,
	[SponsorNameGenderFemale]      BIT             NULL,
	[SponsorNameAnotherNamesYes]      BIT             NULL,
	[SponsorNameAnotherNameNo]      BIT             NULL,
	[SponsorContactEmailAddress]              NVARCHAR (1000) NULL,
	[SponsorContactMobileNumber]              NVARCHAR (1000) NULL,
	[SponsorContactSocialSecurityNumber]              NVARCHAR (1000) NULL,
	[SponsorContactAccountNumber]              NVARCHAR (1000) NULL,
	[SponsorContactDoesNotApply]      BIT             NULL,
	[SponsorContactUncommon]              NVARCHAR (1000) NULL,
	[SponsorContactDifferentPhysicalYes]      BIT             NULL,
	[SponsorContactDifferentPhysicalNo]      BIT             NULL,
	[SponsorPlaceOfBirthDateOfBirth]             DATETIME2 (7)   NULL,
	[SponsorPlaceOfBirthCityOfBirth]              NVARCHAR (1000) NULL,
	[SponsorPlaceOfBirthCountryOfBirthText]              NVARCHAR (1000) NULL,
	[SponsorPlaceOfBirthCountryOfBirthId]              INT NULL,
	[SponsorPlaceOfBirthFatherLastName]              NVARCHAR (1000) NULL,
	[SponsorPlaceOfBirthFatherFirstName]              NVARCHAR (1000) NULL,
	[SponsorPlaceOfBirthFatherMiddleName]              NVARCHAR (1000) NULL,
	[SponsorPlaceOfBirth1DoesNotApply]      BIT             NULL,
	[SponsorPlaceOfBirthFatherDateOfBirth]             DATETIME2 (7)   NULL,
	[SponsorPlaceOfBirth1Unknow]      BIT             NULL,
	[SponsorPlaceOfBirthFatherCountryOfBirth]              INT NULL,
	[SponsorPlaceOfBirthFatherCityProvince]              NVARCHAR (1000) NULL,
	[SponsorPlaceOfBirthHeDeceasedYes]      BIT             NULL,
	[SponsorPlaceOfBirthHeDeceasedNo]      BIT             NULL,
	[SponsorPlaceOfBirthMotherMaidenLastName]              NVARCHAR (1000) NULL,
	[SponsorPlaceOfBirthMotherFirstName]              NVARCHAR (1000) NULL,
	[SponsorPlaceOfBirthMotherMiddleName]              NVARCHAR (1000) NULL,
	[SponsorPlaceOfBirth2DoesNotApply]      BIT             NULL,
	[SponsorPlaceOfBirthMotherDateOfBirth]             DATETIME2 (7)   NULL,
	[SponsorPlaceOfBirth2Unknow]      BIT             NULL,
	[SponsorPlaceOfBirthMotherCountryOfBirth]              INT NULL,
	[SponsorPlaceOfBirthMotherCityOfBirth]              NVARCHAR (1000) NULL,
	[SponsorPlaceOfBirthSheDeceasedYes]      BIT             NULL,
	[SponsorPlaceOfBirthSheDeceasedNo]      BIT             NULL,
	[SponsorStatusUSCitizen]      BIT             NULL,
	[SponsorStatusPermanentResident]      BIT             NULL,
	[SponsorStatusAmericanSamoa]      BIT             NULL,
	[SponsorStatusHeightFeet]              NVARCHAR (1000) NULL,
	[SponsorStatusHeightInches]              NVARCHAR (1000) NULL,
	[SponsorStatusWeightPounds]              NVARCHAR (1000) NULL,
	[SponsorStatusEthnicityNotHispanicOrLatino]      BIT             NULL,
	[SponsorStatusEthnicityHispanicOrLatino]      BIT             NULL,
	[SponsorStatusRaceWhite]      BIT             NULL,
	[SponsorStatusRaceAsian]      BIT             NULL,
	[SponsorStatusRaceBlack]      BIT             NULL,
	[SponsorStatusRaceAmericanIndian]      BIT             NULL,
	[SponsorStatusRaceNativeHawaiian]      BIT             NULL,
	[SponsorStatusHairColorBlack]      BIT             NULL,
	[SponsorStatusHairColorBrown]      BIT             NULL,
	[SponsorStatusHairColorBlond]      BIT             NULL,
	[SponsorStatusHairColorGray]      BIT             NULL,
	[SponsorStatusHairColorWhite]      BIT             NULL,
	[SponsorStatusHairColorRed]      BIT             NULL,
	[SponsorStatusHairColorSandy]      BIT             NULL,
	[SponsorStatusHairColorBald]      BIT             NULL,
	[SponsorStatusHairColorOther]      BIT             NULL,
	[SponsorStatusEyeColorBlack]      BIT             NULL,
	[SponsorStatusEyeColorBlue]      BIT             NULL,
	[SponsorStatusEyeColorBrown]      BIT             NULL,
	[SponsorStatusEyeColorGray]      BIT             NULL,
	[SponsorStatusEyeColorGreen]      BIT             NULL,
	[SponsorStatusEyeColorHazel]      BIT             NULL,
	[SponsorStatusEyeColorMaroon]      BIT             NULL,
	[SponsorStatusEyeColorPink]      BIT             NULL,
	[SponsorStatusEyeColorOther]      BIT             NULL,
	[SponsorMaritalStatusMarried]      BIT             NULL,
	[SponsorMaritalStatusSingle]      BIT             NULL,
	[SponsorMaritalStatusWidowed]      BIT             NULL,
	[SponsorMaritalStatusDivorced]      BIT             NULL,
	[SponsorMaritalStatusChildrenUnder18Yes]      BIT             NULL,
	[SponsorMaritalStatusChildrenUnder18No]      BIT             NULL,
	[SponsorOtherFilingsI129FYes]      BIT             NULL,
	[SponsorOtherFilingsI129FNo]      BIT             NULL,
	[MilitaryAndConvictionsUnitedStatesArmedForcesYes]      BIT             NULL,
	[MilitaryAndConvictionsUnitedStatesArmedForcesNo]      BIT             NULL,
	[MilitaryAndConvictionsCivilOrCriminalYes]      BIT             NULL,
	[MilitaryAndConvictionsCivilOrCriminalNo]      BIT             NULL,
	[MilitaryAndConvictionsEitherCivilOrCriminalYes]      BIT             NULL,
	[MilitaryAndConvictionsEitherCivilOrCriminalNo]      BIT             NULL,
	[MilitaryAndConvictionsDomesticViolenceYes]      BIT             NULL,
	[MilitaryAndConvictionsDomesticViolenceNo]      BIT             NULL,
	[MilitaryAndConvictionsHomicideYes]      BIT             NULL,
	[MilitaryAndConvictionsHomicideNo]      BIT             NULL,
	[MilitaryAndConvictionsArrestsOrConvictionsYes]      BIT             NULL,
	[MilitaryAndConvictionsArrestsOrConvictionsNo]      BIT             NULL,
	[MilitaryAndConvictionsTrafficViolationsYes]      BIT             NULL,
	[MilitaryAndConvictionsTrafficViolationsNo]      BIT             NULL,
	[SponsorAddressInCareOfName]              NVARCHAR (1000) NULL,
	[SponsorAddressDoesNotApply]      BIT             NULL,
	[SponsorAddressNumberAndstreet]              NVARCHAR (1000) NULL,
	[SponsorAddressApartmentSuiteId]      INT NULL,
	[SponsorAddressApartmentSuiteNumber]              NVARCHAR (1000) NULL,
	[SponsorAddressTownOrCity]              NVARCHAR (1000) NULL,
	[SponsorAddressCountry]      INT NULL,
	[SponsorAddressUSState]      INT NULL,
	[SponsorAddressProvince]              NVARCHAR (1000) NULL,
	[SponsorAddressDoesNotApply]      BIT             NULL,
	[SponsorAddressPostalCode]              NVARCHAR (1000) NULL,
	[SponsorAddressLivedAddressSince]             DATETIME2 (7)   NULL,
	[SponsorAddressUSStateCountry]      INT NULL,
	[SponsorRelationshipCityFirstTime]              NVARCHAR (1000) NULL,
	[SponsorRelationshipItUSCISYes]      BIT             NULL,
	[SponsorRelationshipUSCISNo]      BIT             NULL,
	[SponsorRelationshipIMBYes]      BIT             NULL,
	[SponsorRelationshipIMBNo]      BIT             NULL,
	[SponsorEmploymentNameEmployer]              NVARCHAR (1000) NULL,
	[SponsorEmploymentOccupation]              NVARCHAR (1000) NULL,
	[SponsorEmploymentNumberAndStreet]              NVARCHAR (1000) NULL,
	[SponsorEmploymentApartment]      INT NULL,
	[SponsorEmploymentApartmentNumber]              NVARCHAR (1000) NULL,
	[SponsorEmploymentTownOrCity]              NVARCHAR (1000) NULL,
	[SponsorEmploymentCountry]      INT NULL,
	[SponsorEmploymentUSState]      INT NULL,
	[SponsorEmploymentProvince]              NVARCHAR (1000) NULL,
	[SponsorEmploymentDoesNotApply]      BIT             NULL,
	[SponsorEmploymentPostalCode]              NVARCHAR (1000) NULL,
	[SponsorEmploymentCategoryJob]      INT NULL,
	[SponsorEmploymentBeganThisJob]             DATETIME2 (7)   NULL,
	[SponsorImmigrationImmigrationProceedingsYes]      BIT             NULL,
	[SponsorImmigrationImmigrationProceedingsNo]      BIT             NULL,
	[SponsorImmigrationCityAndState]              NVARCHAR (1000) NULL,
	[SponsorImmigrationEstimateDate]             DATETIME2 (7)   NULL,
	[SponsorImmigrationTypeProceedingApplyRemoval]      BIT             NULL,
	[SponsorImmigrationTypeProceedingApplyExclusion]      BIT             NULL,
	[SponsorImmigrationTypeProceedingApplyRescission]      BIT             NULL,
	[SponsorImmigrationTypeProceedingApplyJudicial]      BIT             NULL,
	[SponsorLanguages1]              NVARCHAR (1000) NULL,
	[SponsorUSVisitsUSVisaYes]      BIT             NULL,
	[SponsorUSVisitsUSVisaNo]      BIT             NULL,
	[SponsorUSVisitsExplainDeniedAdmissions]              NVARCHAR (1000) NULL,
	[SponsorUSVisitsVisitedUnitedStatesYes]      BIT             NULL,
	[SponsorUSVisitsVisitedUnitedStatesNo]      BIT             NULL,
	[SponsorUSVisitsPrimaryCity]              NVARCHAR (1000) NULL,
	[SponsorUSVisitsTypeOfVisa]      INT NULL,
	[SponsorUSVisitsRegistrationNumber]              NVARCHAR (1000) NULL,
	[SponsorUSVisitsNone]      BIT             NULL,
	[SponsorUSVisitsStartDateVisit]             DATETIME2 (7)   NULL,
	[SponsorUSVisitsEndDateVisit]             DATETIME2 (7)   NULL,
	[SponsorRelativesChildInUSYes]      BIT             NULL,
	[SponsorRelativesChildInUSNo]      BIT             NULL,
	[SponsorRelativesFirstAndMiddleNames]              NVARCHAR (1000) NULL,
	[SponsorRelativesLastName]              NVARCHAR (1000) NULL,
	[SponsorRelativesSuffixAfterName]      INT NULL,
	[SponsorRelativesStatus]      INT NULL,
	[SponsorQuestion1ParamilitaryUnitYes]      BIT             NULL,
	[SponsorQuestion1ParamilitaryUnitNo]      BIT             NULL,
	[SponsorQuestion1ExplainQuestion]              NVARCHAR (1000) NULL,
	[SponsorQuestion1HealthSignificanceYes]      BIT             NULL,
	[SponsorQuestion1HealthSignificanceNo]      BIT             NULL,
	[SponsorQuestion1SafetyOrWelfareYes]      BIT             NULL,
	[SponsorQuestion1SafetyOrWelfareNo]      BIT             NULL,
	[SponsorQuestion1DrugAbuserYes]      BIT             NULL,
	[SponsorQuestion1DrugAbuserNo]      BIT             NULL,
	[SponsorQuestion1NecessaryVaccinationsYes]      BIT             NULL,
	[SponsorQuestion1NecessaryVaccinationsNo]      BIT             NULL,
	[SponsorQuestion1ArrestedOffenseYes]      BIT             NULL,
	[SponsorQuestion1ArrestedOffenseNo]      BIT             NULL,
	[SponsorQuestion1ViolatedYes]      BIT             NULL,
	[SponsorQuestion1ViolatedNo]      BIT             NULL,
	[SponsorQuestion1EngageInProstitutionYes]      BIT             NULL,
	[SponsorQuestion1EngageInProstitutionNo]      BIT             NULL,
	[SponsorQuestion1MoneyLaunderingYes]      BIT             NULL,
	[SponsorQuestion1MoneyLaunderingNo]      BIT             NULL,
	[SponsorQuestion1HumanTraffickingOffenseYes]      BIT             NULL,
	[SponsorQuestion1HumanTraffickingOffenseNo]      BIT             NULL,
	[SponsorQuestion1KnowinglyAidedYes]      BIT             NULL,
	[SponsorQuestion1KnowinglyAidedNo]      BIT             NULL,
	[SponsorQuestion2KnowinglyAidedYes]      BIT             NULL,
	[SponsorQuestion2KnowinglyAidedNo]      BIT             NULL,
	[SponsorQuestion2ExplainQuestion]              NVARCHAR (1000) NULL,
	[SponsorQuestion2TraffickingOffenseYes]      BIT             NULL,
	[SponsorQuestion2TraffickingOffenseNo]      BIT             NULL,
	[SponsorQuestion2IdentifiedPresidentYes]      BIT             NULL,
	[SponsorQuestion2IdentifiedPresidentNo]      BIT             NULL,
	[SponsorQuestion2ViolatedYes]      BIT             NULL,
	[SponsorQuestion2ViolatedNo]      BIT             NULL,
	[SponsorQuestion2EngageEspionageYes]      BIT             NULL,
	[SponsorQuestion2EngageEspionageNo]      BIT             NULL,
	[SponsorQuestion2TerroristActivitiesYes]      BIT             NULL,
	[SponsorQuestion2TerroristActivitiesNo]      BIT             NULL,
	[SponsorQuestion2FinancialAssistanceYes]      BIT             NULL,
	[SponsorQuestion2FinancialAssistanceNo]      BIT             NULL,
	[SponsorQuestion2TerroristOrganizationYes]      BIT             NULL,
	[SponsorQuestion2TerroristOrganizationNo]      BIT             NULL,
	[SponsorQuestion2GenocideYes]      BIT             NULL,
	[SponsorQuestion2GenocideNo]      BIT             NULL,
	[SponsorQuestion2TortureYes]      BIT             NULL,
	[SponsorQuestion2TortureNo]      BIT             NULL,
	[SponsorQuestion2IntentionallyAssistedYes]      BIT             NULL,
	[SponsorQuestion2IntentionallyAssistedNo]      BIT             NULL,
	[SponsorQuestion3JudicialKillingsYes]      BIT             NULL,
	[SponsorQuestion3JudicialKillingsNo]      BIT             NULL,
	[SponsorQuestion3ExplainQuestion]              NVARCHAR (1000) NULL,
	[SponsorQuestion3EngagedRecruitmentYes]      BIT             NULL,
	[SponsorQuestion3EngagedRecruitmentNo]      BIT             NULL,
	[SponsorQuestion3ReligiousFreedomYes]      BIT             NULL,
	[SponsorQuestion3ReligiousFreedomNo]      BIT             NULL,
	[SponsorQuestion3TotalitarianPartyYes]      BIT             NULL,
	[SponsorQuestion3TotalitarianPartyNo]      BIT             NULL,
	[SponsorQuestion3IndirectlyAssistedYes]      BIT             NULL,
	[SponsorQuestion3IndirectlyAssistedNo]      BIT             NULL,
	[SponsorQuestion31ClaimOwnershipYes]      BIT             NULL,
	[SponsorQuestion31ClaimOwnershipNo]      BIT             NULL,
	[SponsorQuestion32ClaimOwnershipYes]      BIT             NULL,
	[SponsorQuestion32ClaimOwnershipNo]      BIT             NULL,
	[SponsorQuestion31ChemicalWeaponsYes]      BIT             NULL,
	[SponsorQuestion31ChemicalWeaponsNo]      BIT             NULL,
	[SponsorQuestion32ChemicalWeaponsYes]      BIT             NULL,
	[SponsorQuestion32ChemicalWeaponsNo]      BIT             NULL,
	[SponsorQuestion3EstablishmentYes]      BIT             NULL,
	[SponsorQuestion3EstablishmentNo]      BIT             NULL,
	[SponsorQuestion3ReimbursingSchoolYes]      BIT             NULL,
	[SponsorQuestion3ReimbursingSchoolNo]      BIT             NULL,
	[SponsorQuestion4BodilyTissueYes]      BIT             NULL,
	[SponsorQuestion4BodilyTissueNo]      BIT             NULL,
	[SponsorQuestion4ExplainQuestion]              NVARCHAR (1000) NULL,
	[SponsorQuestion4INA274CYes]      BIT             NULL,
	[SponsorQuestion4INA274CNo]      BIT             NULL,
	[SponsorQuestion4RemovedUS5YearsYes]      BIT             NULL,
	[SponsorQuestion4RemovedUS5YearsNo]      BIT             NULL,
	[SponsorQuestion4RemovedUS20YearsYes]      BIT             NULL,
	[SponsorQuestion4RemovedUS20YearsNo]      BIT             NULL,
	[SponsorQuestion4RemovedUS10YearsYes]      BIT             NULL,
	[SponsorQuestion4RemovedUS10YearsNo]      BIT             NULL,
	[SponsorQuestion4ConvictedRemovedUSYes]      BIT             NULL,
	[SponsorQuestion4ConvictedRemovedUSNo]      BIT             NULL,
	[SponsorQuestion4Unlawfully180DaysYes]      BIT             NULL,
	[SponsorQuestion4Unlawfully180DaysNo]      BIT             NULL,
	[SponsorQuestion4Unlawfully1YearYes]      BIT             NULL,
	[SponsorQuestion4Unlawfully1YearNo]      BIT             NULL,
	[SponsorQuestion4WithheldCustodyYes]      BIT             NULL,
	[SponsorQuestion4WithheldCustodyNo]      BIT             NULL,
	[SponsorQuestion4ViolationLawYes]      BIT             NULL,
	[SponsorQuestion4ViolationLawNo]      BIT             NULL,
	[SponsorQuestion5AvoidingTaxationYes]      BIT             NULL,
	[SponsorQuestion5AvoidingTaxationNo]      BIT             NULL,
	[SponsorQuestion5ExplainQuestion]              NVARCHAR (1000) NULL,
	[SponsorQuestion5FormerExchangeVisitorYes]      BIT             NULL,
	[SponsorQuestion5FormerExchangeVisitorNo]      BIT             NULL,
	[SponsorQuestion5SecretaryLaborYes]      BIT             NULL,
	[SponsorQuestion5SecretaryLaborNo]      BIT             NULL,
	[SponsorQuestion5ForeignMedicalSchoolYes]      BIT             NULL,
	[SponsorQuestion5ForeignMedicalSchoolNo]      BIT             NULL,
	[SponsorQuestion5HealthCareWorkerYes]      BIT             NULL,
	[SponsorQuestion5HealthCareWorkerNo]      BIT             NULL,
	[SponsorQuestion5PermanentlyIneligibleYes]      BIT             NULL,
	[SponsorQuestion5PermanentlyIneligibleNo]      BIT             NULL,
	[SponsorQuestion5EvadeMilitaryServiceYes]      BIT             NULL,
	[SponsorQuestion5EvadeMilitaryServiceNo]      BIT             NULL,
	[SponsorQuestion5PracticePolygamyYes]      BIT             NULL,
	[SponsorQuestion5PracticePolygamyNo]      BIT             NULL,
	[SponsorQuestion5SecretaryHomelandYes]      BIT             NULL,
	[SponsorQuestion5SecretaryHomelandNo]      BIT             NULL,
	[SponsorQuestion5ObtainVisaYes]      BIT             NULL,
	[SponsorQuestion5ObtainVisaNo]      BIT             NULL,
    	[Deleted] BIT CONSTRAINT [DF_FormVisaSpouse_Deleted] DEFAULT ((0)) NOT NULL,
    	CONSTRAINT [PK_FormVisaSpouse] PRIMARY KEY CLUSTERED ([Id] ASC)
);
