CREATE TABLE [dbo].[FormVisaFiance] (
    	[Id] BIGINT IDENTITY (1, 1) NOT NULL,
    	[AccountId] BIGINT NULL,    
	[PetitionerContactFirstName] NVARCHAR (1000) NULL,
	[PetitionerContactMiddleName] NVARCHAR (1000) NULL,
	[PetitionerContactLastName] NVARCHAR (1000) NULL,
	[PetitionerContactOtherNamesUsedYes] BIT             NULL,
	[PetitionerContactOtherNamesUsedNo] BIT             NULL,
	[PetitionerContactEmailAddress] NVARCHAR (1000) NULL,
	[PetitionerContactRelatedFianceYes] BIT             NULL,
	[PetitionerContactRelatedFianceNo] BIT             NULL,
	[PetitionerAddress1MailingStreetAddressApt] BIT             NULL,
	[PetitionerAddress1MailingStreetAddressSte] BIT             NULL,
	[PetitionerAddress1MailingStreetAddressFlr] BIT             NULL,
	[PetitionerAddressCityOrTown] NVARCHAR (1000) NULL,
	[PetitionerAddress1State] NVARCHAR (1000) NULL,
	[PetitionerAddress1Province] NVARCHAR (1000) NULL,
	[PetitionerAddress1ZipCode] NVARCHAR (1000) NULL,
	[PetitionerAddress1Country] NVARCHAR (1000) NULL,
	[PetitionerAddressDifferentPhysicalAddressYes] BIT             NULL,
	[PetitionerAddressDifferentPhysicalAddressNo] BIT             NULL,
	[PetitionerAddress2MailingStreetAddressApt] BIT             NULL,
	[PetitionerAddress2MailingStreetAddressSte] BIT             NULL,
	[PetitionerAddress2MailingStreetAddressFlr] BIT             NULL,
	[PetitionerAddressMailingStreetAddressYes] BIT             NULL,
	[PetitionerAddress2State] NVARCHAR (1000) NULL,
	[PetitionerAddress2Province] NVARCHAR (1000) NULL,
	[PetitionerAddress2ZipCode] NVARCHAR (1000) NULL,
	[PetitionerAddress2Country] NVARCHAR (1000) NULL,
	[PetitionerAddressResidence1State] NVARCHAR (1000) NULL,
	[PetitionerAddressResidence1Country] NVARCHAR (1000) NULL,
	[PetitionerAddressResidence2State] NVARCHAR (1000) NULL,
	[PetitionerAddressResidence2Country] NVARCHAR (1000) NULL,
	[PetitionerEmploymentNameOfEmployer] NVARCHAR (1000) NULL,
	[PetitionerEmploymentStreetAddress] NVARCHAR (1000) NULL,
	[PetitionerEmploymentCityOrTown] NVARCHAR (1000) NULL,
	[PetitionerEmploymentState] NVARCHAR (1000) NULL,
	[PetitionerEmploymentProvince] NVARCHAR (1000) NULL,
	[PetitionerEmploymentZipCode] NVARCHAR (1000) NULL,
	[PetitionerEmploymentCountry] NVARCHAR (1000) NULL,
	[PetitionerEmploymentOccupationName] NVARCHAR (1000) NULL,
	[PetitionerEmploymentStartDate] DATETIME2 (7)   NULL,
	[PetitionerEmploymentEndDate] DATETIME2 (7)   NULL,
	[PetitionerBackgroundGenderMale] BIT             NULL,
	[PetitionerBackgroundGenderFemale] BIT             NULL,
	[PetitionerBackgroundDateOfBirth] DATETIME2 (7)   NULL,
	[PetitionerBackgroundMaritalStatusSingle] BIT             NULL,
	[PetitionerBackgroundMaritalStatusMarried] BIT             NULL,
	[PetitionerBackgroundMaritalStatusDivorced] BIT             NULL,
	[PetitionerBackgroundMaritalStatusWidowed] BIT             NULL,
	[PetitionerBackgroundCityOfBirth] NVARCHAR (1000) NULL,
	[PetitionerBackgroundStateOfBirth] NVARCHAR (1000) NULL,
	[PetitionerBackgroundCountryOfBirth] NVARCHAR (1000) NULL,
	[PetitionerBackgroundPreviouslyMarriedYes] BIT             NULL,
	[PetitionerBackgroundPreviouslyMarriedNo] BIT             NULL,
	[PetitionerParent1FirstName] NVARCHAR (1000) NULL,
	[PetitionerParent1MiddleName] NVARCHAR (1000) NULL,
	[PetitionerParent1LastName] NVARCHAR (1000) NULL,
	[PetitionerParent1DateOfBirth] DATETIME2 (7)   NULL,
	[PetitionerParent1GenderMale] BIT             NULL,
	[PetitionerParent1GenderFemale] BIT             NULL,
	[PetitionerParent1CountryOfBirth] INT             NULL,
	[PetitionerParent1CityOfBirth] NVARCHAR (1000) NULL,
	[PetitionerParent1CountryOfResidence] NVARCHAR (1000) NULL,
	[PetitionerParent2FirstName] NVARCHAR (1000) NULL,
	[PetitionerParent2MiddleName] NVARCHAR (1000) NULL,
	[PetitionerParent2LastName] NVARCHAR (1000) NULL,
	[PetitionerParent2DateOfBirth] DATETIME2 (7)   NULL,
	[PetitionerParent2GenderMale] BIT             NULL,
	[PetitionerParent2GenderFemale] BIT             NULL,
	[PetitionerParent2CountryOfBirth] INT             NULL,
	[PetitionerParent2CityOfBirth] NVARCHAR (1000) NULL,
	[PetitionerParent2CountryOfResidence] NVARCHAR (1000) NULL,
	[PetitionerBiographicEthnicityNotHispanic] BIT             NULL,
	[PetitionerBiographicEthnicityHispanic] BIT             NULL,
	[PetitionerBiographicRaceWhite] BIT             NULL,
	[PetitionerBiographicRaceAsian] BIT             NULL,
	[PetitionerBiographicRaceBlack] BIT             NULL,
	[PetitionerBiographicRaceIndian] BIT             NULL,
	[PetitionerBiographicRaceHawaiian] BIT             NULL,
	[PetitionerBiographicFeet] NVARCHAR (1000) NULL,
	[PetitionerBiographicInches] NVARCHAR (1000) NULL,
	[PetitionerBiographicPound] NVARCHAR (1000) NULL,
	[PetitionerBiographicHairColorBlack] BIT             NULL,
	[PetitionerBiographicHairColorBrown] BIT             NULL,
	[PetitionerBiographicHairColorBlond] BIT             NULL,
	[PetitionerBiographicHairColorGray] BIT             NULL,
	[PetitionerBiographicHairColorWhite] BIT             NULL,
	[PetitionerBiographicHairColorRed] BIT             NULL,
	[PetitionerBiographicHairColorSandy] BIT             NULL,
	[PetitionerBiographicHairColorBald] BIT             NULL,
	[PetitionerBiographicHairColorOther] BIT             NULL,
	[PetitionerBiographicEyeColorBlack] BIT             NULL,
	[PetitionerBiographicEyeColorBlue] BIT             NULL,
	[PetitionerBiographicEyeColorBrown] BIT             NULL,
	[PetitionerBiographicEyeColorGray] BIT             NULL,
	[PetitionerBiographicEyeColorGreen] BIT             NULL,
	[PetitionerBiographicEyeColorHazel] BIT             NULL,
	[PetitionerBiographicEyeColorMaroon] BIT             NULL,
	[PetitionerBiographicEyeColorPink] BIT             NULL,
	[PetitionerBiographicEyeColorOther] BIT             NULL,
	[PetitionerBiographicCivilCriminalYes] BIT             NULL,
	[PetitionerBiographicCivilCriminalNo)] BIT             NULL,
	[PetitionerBiographicDomesticViolenceYes] BIT             NULL,
	[PetitionerBiographicDomesticViolenceNo] BIT             NULL,
	[PetitionerBiographicHomicideYes] BIT             NULL,
	[PetitionerBiographicHomicideNo] BIT             NULL,
	[PetitionerBiographicConvictionsYes] BIT             NULL,
	[PetitionerBiographicConvictionsNo] BIT             NULL,
	[PetitionerStatusSocialSecurityNumber] NVARCHAR (1000) NULL,
	[PetitionerStatusThroughBirthUS] BIT             NULL,
	[PetitionerStatusThroughUSCitizenParents] BIT             NULL,
	[PetitionerStatusThroughNaturalization] BIT             NULL,
	[PetitionerStatusCitizenshipYes] BIT             NULL,
	[PetitionerStatusCitizenshipNo] BIT             NULL,
	[PetitionerStatusI129FYes] BIT             NULL,
	[PetitionerStatusI129FNo] BIT             NULL,
	[PetitionerStatusIMBYes] BIT             NULL,
	[PetitionerStatusIMBNo] BIT             NULL,
	[PetitionerStatusCity] NVARCHAR (1000) NULL,
	[PetitionerStatusCountry] NVARCHAR (1000) NULL,
	[BeneficiaryContactFirstName] NVARCHAR (1000) NULL,
	[BeneficiaryContactMiddleName] NVARCHAR (1000) NULL,
	[BeneficiaryContactLastName] NVARCHAR (1000) NULL,
	[BeneficiaryContactOtherNamesUsedYes] BIT             NULL,
	[BeneficiaryContactOtherNamesUsedNo] BIT             NULL,
	[BeneficiaryContactDaytimePhoneNumber] NVARCHAR (1000) NULL,
	[BeneficiaryContactEmailAddress] NVARCHAR (1000) NULL,
	[BeneficiaryAddress1MailingStreetAddressApt] BIT             NULL,
	[BeneficiaryAddress1MailingStreetAddressSte] BIT             NULL,
	[BeneficiaryAddress1MailingStreetAddressFlr] BIT             NULL,
	[BeneficiaryAddress1MailingStreetAddressYes] BIT             NULL,
	[BeneficiaryAddress1CityOrTown] NVARCHAR (1000) NULL,
	[BeneficiaryAddress1State] NVARCHAR (1000) NULL,
	[BeneficiaryAddress1Province] NVARCHAR (1000) NULL,
	[BeneficiaryAddress1ZipCode] NVARCHAR (1000) NULL,
	[BeneficiaryAddress1Country] NVARCHAR (1000) NULL,
	[BeneficiaryAddressDifferentPhysicalYes] BIT             NULL,
	[BeneficiaryAddressDifferentPhysicalNo] BIT             NULL,
	[BeneficiaryAddress2MailingStreetAddressApt] BIT             NULL,
	[BeneficiaryAddress2MailingStreetAddressSte] BIT             NULL,
	[BeneficiaryAddress2MailingStreetAddressFlr] BIT             NULL,
	[BeneficiaryAddress2MailingStreetAddressYes] BIT             NULL,
	[BeneficiaryAddress2CityOrTown] NVARCHAR (1000) NULL,
	[BeneficiaryAddress2State] NVARCHAR (1000) NULL,
	[BeneficiaryAddress2Province] NVARCHAR (1000) NULL,
	[BeneficiaryAddress2ZipCode] NVARCHAR (1000) NULL,
	[BeneficiaryAddress2Country] NVARCHAR (1000) NULL,
	[BeneficiaryAddressResidence1State] NVARCHAR (1000) NULL,
	[BeneficiaryAddressResidence1Country] NVARCHAR (1000) NULL,
	[BeneficiaryAddressResidence2State] NVARCHAR (1000) NULL,
	[BeneficiaryAddressResidence2Country] NVARCHAR (1000) NULL,
	[BeneficiaryEmploymentNameOfEmployer] NVARCHAR (1000) NULL,
	[BeneficiaryEmploymentStreetAddress] NVARCHAR (1000) NULL,
	[BeneficiaryEmploymentCityOrTown] NVARCHAR (1000) NULL,
	[BeneficiaryEmploymentState] NVARCHAR (1000) NULL,
	[BeneficiaryEmploymentProvince] NVARCHAR (1000) NULL,
	[BeneficiaryEmploymentZipCode] NVARCHAR (1000) NULL,
	[BeneficiaryEmploymentCountry] NVARCHAR (1000) NULL,
	[BeneficiaryEmploymentOccupationName] NVARCHAR (1000) NULL,
	[BeneficiaryEmploymentStartDate] DATETIME2 (7)   NULL,
	[BeneficiaryEmploymentEndDate] DATETIME2 (7)   NULL,
	[BeneficiaryBackgroundGenderMale] BIT             NULL,
	[BeneficiaryBackgroundGenderFemale] BIT             NULL,
	[BeneficiaryBackgroundDateOfBirth] DATETIME2 (7)   NULL,
	[BeneficiaryBackgroundMaritalStatusSingle] BIT             NULL,
	[BeneficiaryBackgroundMaritalStatusMarried] BIT             NULL,
	[BeneficiaryBackgroundMaritalStatusDivorced] BIT             NULL,
	[BeneficiaryBackgroundMaritalStatusWidowed] BIT             NULL,
	[BeneficiaryBackgroundCityOfBirth] NVARCHAR (1000) NULL,
	[BeneficiaryBackgroundProvinceOfBirth] NVARCHAR (1000) NULL,
	[BeneficiaryBackgroundCountryOfBirth] NVARCHAR (1000) NULL,
	[BeneficiaryBackgroundPreviouslyMarriedYes] BIT             NULL,
	[BeneficiaryBackgroundPreviouslyMarriedNo] BIT             NULL,
	[BeneficiaryBackgroundEverBeenInTheUSYes] BIT             NULL,
	[BeneficiaryBackgroundEverBeenInTheUSNo] BIT             NULL,
	[BeneficiaryBackgroundCurrentlyInUSYes] BIT             NULL,
	[BeneficiaryBackgroundCurrentlyInUSNo] BIT             NULL,
	[BeneficiaryAbroadStreetAddressApt] BIT             NULL,
	[BeneficiaryAbroadStreetAddressSte] BIT             NULL,
	[BeneficiaryAbroadStreetAddressFlo] BIT             NULL,
	[BeneficiaryAbroadStreetAddressNumber] BIT             NULL,
	[BeneficiaryAbroadStreetAddressText] NVARCHAR (1000) NULL,
	[BeneficiaryAbroadCityOrTown] NVARCHAR (1000) NULL,
	[BeneficiaryAbroadState] NVARCHAR (1000) NULL,
	[BeneficiaryAbroadProvince] NVARCHAR (1000) NULL,
	[BeneficiaryAbroadZipCode] NVARCHAR (1000) NULL,
	[BeneficiaryAbroadCountry] NVARCHAR (1000) NULL,
	[BeneficiaryAbroadDaytimePhoneNumber] NVARCHAR (1000) NULL,
	[BeneficiaryAbroadLatinAlphabetYes] BIT             NULL,
	[BeneficiaryAbroadLatinAlphabetNo] BIT             NULL,
	[BeneficiaryAbroadOtherNamesUsedYes] BIT             NULL,
	[BeneficiaryAbroadOtherNamesUsedNo] BIT             NULL,
	[InterpreterFirstName] NVARCHAR (1000) NULL,
	[InterpreterLastName] NVARCHAR (1000) NULL,
	[InterpreterBusinessName] NVARCHAR (1000) NULL,
	[InterpreterStreetAddressApt] BIT             NULL,
	[InterpreterStreetAddressSte] BIT             NULL,
	[InterpreterStreetAddressFlo] BIT             NULL,
	[InterpreterStreetAddressNumber] BIT             NULL,
	[InterpreterStreetAddressText] NVARCHAR (1000) NULL,
	[InterpreterCityOrTown] NVARCHAR (1000) NULL,
	[InterpreterProvince] NVARCHAR (1000) NULL,
	[InterpreterZipCode] NVARCHAR (1000) NULL,
	[InterpreterCountry] NVARCHAR (1000) NULL,
	[InterpreterDaytimePhoneNumber] NVARCHAR (1000) NULL,
	[InterpreterEmailAddress] NVARCHAR (1000) NULL,
    	[Deleted] BIT CONSTRAINT [DF_FormVisaFiance_Deleted] DEFAULT ((0)) NOT NULL,
    	CONSTRAINT [PK_FormVisaFiance] PRIMARY KEY CLUSTERED ([Id] ASC)
);
