CREATE TABLE [dbo].[FormVisaSpouse] (
   	[Id] BIGINT IDENTITY (1, 1) NOT NULL,
    	[AccountId] BIGINT NULL,
	[PetitionerNameFirstName]              NVARCHAR (1000) NULL,
	[PetitionerNameMiddleName]              NVARCHAR (1000) NULL,
	[PetitionerNameDoesNotApply]      BIT             NULL,
	[PetitionerNameLastName]              NVARCHAR (1000) NULL,
	[PetitionerNameDaytimePhoneNumber]              NVARCHAR (1000) NULL,
	[PetitionerNameGenderMale]      BIT             NULL,
	[PetitionerNameGenderFemale]      BIT             NULL,
	[PetitionerNameAnotherNameYes]      BIT             NULL,
	[PetitionerNameAnotherNameNo]      BIT             NULL,
	[PetitionerContactEmailAddress]              NVARCHAR (1000) NULL,
	[PetitionerContactMobileNumber]              NVARCHAR (1000) NULL,
	[PetitionerContactSocialSecurityNumber]              NVARCHAR (1000) NULL,
	[PetitionerContactAccountNumber]              NVARCHAR (1000) NULL,
	[PetitionerContactDoesNotApply]      BIT             NULL,
	[PetitionerContactUncommon]              NVARCHAR (1000) NULL,
	[PetitionerContactDifferentPhysicalYes]      BIT             NULL,
	[PetitionerContactDifferentPhysicalNo]      BIT             NULL,
	[PetitionerPlaceOfBirthDateOfBirth]             DATETIME2 (7)   NULL,
	[PetitionerPlaceOfBirthCityOfBirth]              NVARCHAR (1000) NULL,
	[PetitionerPlaceOfBirthCountryOfBirthText]              NVARCHAR (1000) NULL,
	[PetitionerPlaceOfBirthCountryOfBirthId]              INT NULL,
	[PetitionerPlaceOfBirthFatherLastName]              NVARCHAR (1000) NULL,
	[PetitionerPlaceOfBirthFatherFirstName]              NVARCHAR (1000) NULL,
	[PetitionerPlaceOfBirthFatherMiddleName]              NVARCHAR (1000) NULL,
	[PetitionerPlaceOfBirth1DoesNotApply]      BIT             NULL,
	[PetitionerPlaceOfBirthFatherDateOfBirth]             DATETIME2 (7)   NULL,
	[PetitionerPlaceOfBirth1Unknow]      BIT             NULL,
	[PetitionerPlaceOfBirthFatherCountryOfBirth]              INT NULL,
	[PetitionerPlaceOfBirthFatherCityProvince]              NVARCHAR (1000) NULL,
	[PetitionerPlaceOfBirthHeDeceasedYes]      BIT             NULL,
	[PetitionerPlaceOfBirthHeDeceasedNo]      BIT             NULL,
	[PetitionerPlaceOfBirthMotherMaidenLastName]              NVARCHAR (1000) NULL,
	[PetitionerPlaceOfBirthMotherFirstName]              NVARCHAR (1000) NULL,
	[PetitionerPlaceOfBirthMotherMiddleName]              NVARCHAR (1000) NULL,
	[PetitionerPlaceOfBirth2DoesNotApply]      BIT             NULL,
	[PetitionerPlaceOfBirthMotherDateOfBirth]             DATETIME2 (7)   NULL,
	[PetitionerPlaceOfBirth2Unknow]      BIT             NULL,
	[PetitionerPlaceOfBirthMotherCountryOfBirth]              INT NULL,
	[PetitionerPlaceOfBirthMotherCityOfBirth]              NVARCHAR (1000) NULL,
	[PetitionerPlaceOfBirthSheDeceasedYes]      BIT             NULL,
	[PetitionerPlaceOfBirthSheDeceasedNo]      BIT             NULL,
	[PetitionerStatusUSCitizen]      BIT             NULL,
	[PetitionerStatusPermanentResident]      BIT             NULL,
	[PetitionerStatusAmericanSamoa]      BIT             NULL,
	[PetitionerStatusHeightFeet]              NVARCHAR (1000) NULL,
	[PetitionerStatusHeightInches]              NVARCHAR (1000) NULL,
	[PetitionerStatusWeightPounds]              NVARCHAR (1000) NULL,
	[PetitionerStatusEthnicityNotHispanicOrLatino]      BIT             NULL,
	[PetitionerStatusEthnicityHispanicOrLatino]      BIT             NULL,
	[PetitionerStatusRaceWhite]      BIT             NULL,
	[PetitionerStatusRaceAsian]      BIT             NULL,
	[PetitionerStatusRaceBlack]      BIT             NULL,
	[PetitionerStatusRaceAmericanIndian]      BIT             NULL,
	[PetitionerStatusRaceNativeHawaiian]      BIT             NULL,
	[PetitionerStatusHairColorBlack]      BIT             NULL,
	[PetitionerStatusHairColorBrown]      BIT             NULL,
	[PetitionerStatusHairColorBlond]      BIT             NULL,
	[PetitionerStatusHairColorGray]      BIT             NULL,
	[PetitionerStatusHairColorWhite]      BIT             NULL,
	[PetitionerStatusHairColorRed]      BIT             NULL,
	[PetitionerStatusHairColorSandy]      BIT             NULL,
	[PetitionerStatusHairColorBald]      BIT             NULL,
	[PetitionerStatusHairColorOther]      BIT             NULL,
	[PetitionerStatusEyeColorBlack]      BIT             NULL,
	[PetitionerStatusEyeColorBlue]      BIT             NULL,
	[PetitionerStatusEyeColorBrown]      BIT             NULL,
	[PetitionerStatusEyeColorGray]      BIT             NULL,
	[PetitionerStatusEyeColorGreen]      BIT             NULL,
	[PetitionerStatusEyeColorHazel]      BIT             NULL,
	[PetitionerStatusEyeColorMaroon]      BIT             NULL,
	[PetitionerStatusEyeColorPink]      BIT             NULL,
	[PetitionerStatusEyeColorOther]      BIT             NULL,
	[PetitionerMaritalStatusMarried]      BIT             NULL,
	[PetitionerMaritalStatusSingle]      BIT             NULL,
	[PetitionerMaritalStatusWidowed]      BIT             NULL,
	[PetitionerMaritalStatusDivorced]      BIT             NULL,
	[PetitionerMaritalStatusChildrenUnder18Yes]      BIT             NULL,
	[PetitionerMaritalStatusChildrenUnder18No]      BIT             NULL,
	[PetitionerOtherFilingsI129FYes]      BIT             NULL,
	[PetitionerOtherFilingsI129FNo]      BIT             NULL,
	[MilitaryAndConvictionsUnitedStatesArmedForcesYes]      BIT             NULL,
	[MilitaryAndConvictionsUnitedStatesArmedForcesNo]      BIT             NULL,
	[MilitaryAndConvictionsCivilOrCriminalYes]      BIT             NULL,
	[MilitaryAndConvictionsCivilOrCriminalNo]      BIT             NULL,
	[MilitaryAndConvictionsEitherCivilOrCriminalYes]      BIT             NULL,
	[MilitaryAndConvictionsEitherCivilOrCriminalNo]      BIT             NULL,
	[MilitaryAndConvictionsDomesticViolenceYes]      BIT             NULL,
	[MilitaryAndConvictionsDomesticViolenceNo]      BIT             NULL,
	[MilitaryAndConvictionsHomicideYes]      BIT             NULL,
	[MilitaryAndConvictionsHomicideNo]      BIT             NULL,
	[MilitaryAndConvictionsArrestsOrConvictionsYes]      BIT             NULL,
	[MilitaryAndConvictionsArrestsOrConvictionsNo]      BIT             NULL,
	[MilitaryAndConvictionsTrafficViolationsYes]      BIT             NULL,
	[MilitaryAndConvictionsTrafficViolationsNo]      BIT             NULL,
	[PetitionerAddressInCareOfName]              NVARCHAR (1000) NULL,
	[PetitionerAddress1DoesNotApply]      BIT             NULL,
	[PetitionerAddressNumberAndstreet]              NVARCHAR (1000) NULL,
	[PetitionerAddressApartmentSuiteId]      INT NULL,
	[PetitionerAddressApartmentSuiteNumber]              NVARCHAR (1000) NULL,
	[PetitionerAddressTownOrCity]              NVARCHAR (1000) NULL,
	[PetitionerAddressCountry]      INT NULL,
	[PetitionerAddressUSState]      INT NULL,
	[PetitionerAddressProvince]              NVARCHAR (1000) NULL,
	[PetitionerAddress2DoesNotApply]      BIT             NULL,
	[PetitionerAddressPostalCode]              NVARCHAR (1000) NULL,
	[PetitionerAddressLivedAddressSince]             DATETIME2 (7)   NULL,
	[PetitionerAddressUSStateCountry]      INT NULL,
	[PetitionerRelationshipCityFirstTime]              NVARCHAR (1000) NULL,
	[PetitionerRelationshipUSCISYes]      BIT             NULL,
	[PetitionerRelationshipUSCISNo]      BIT             NULL,
	[PetitionerRelationshipIMBYes]      BIT             NULL,
	[PetitionerRelationshipIMBNo]      BIT             NULL,
	[PetitionerEmploymentNameEmployer]              NVARCHAR (1000) NULL,
	[PetitionerEmploymentOccupation]              NVARCHAR (1000) NULL,
	[PetitionerEmploymentNumberAndStreet]              NVARCHAR (1000) NULL,
	[PetitionerEmploymentApartment]      INT NULL,
	[PetitionerEmploymentApartmentNumber]              NVARCHAR (1000) NULL,
	[PetitionerEmploymentTownOrCity]              NVARCHAR (1000) NULL,
	[PetitionerEmploymentCountry]      INT NULL,
	[PetitionerEmploymentUSState]      INT NULL,
	[PetitionerEmploymentProvince]              NVARCHAR (1000) NULL,
	[PetitionerEmploymentDoesNotApply]      BIT             NULL,
	[PetitionerEmploymentPostalCode]              NVARCHAR (1000) NULL,
	[PetitionerEmploymentCategoryJob]      INT NULL,
	[PetitionerEmploymentBeganThisJob]             DATETIME2 (7)   NULL,
	[PetitionerImmigrationImmigrationProceedingsYes]      BIT             NULL,
	[PetitionerImmigrationImmigrationProceedingsNo]      BIT             NULL,
	[PetitionerImmigrationCityAndState]              NVARCHAR (1000) NULL,
	[PetitionerImmigrationEstimateDate]             DATETIME2 (7)   NULL,
	[PetitionerImmigrationTypeProceedingApplyRemoval]      BIT             NULL,
	[PetitionerImmigrationTypeProceedingApplyExclusion]      BIT             NULL,
	[PetitionerImmigrationTypeProceedingApplyRescission]      BIT             NULL,
	[PetitionerImmigrationTypeProceedingApplyJudicial]      BIT             NULL,
	[PetitionerLanguages1]              NVARCHAR (1000) NULL,
	[PetitionerUSVisitsUSVisaYes]      BIT             NULL,
	[PetitionerUSVisitsUSVisaNo]      BIT             NULL,
	[PetitionerUSVisitsExplainDeniedAdmissions]              NVARCHAR (1000) NULL,
	[PetitionerUSVisitsVisitedUnitedStatesYes]      BIT             NULL,
	[PetitionerUSVisitsVisitedUnitedStatesNo]      BIT             NULL,
	[PetitionerUSVisitsPrimaryCity]              NVARCHAR (1000) NULL,
	[PetitionerUSVisitsTypeOfVisa]      INT NULL,
	[PetitionerUSVisitsRegistrationNumber]              NVARCHAR (1000) NULL,
	[PetitionerUSVisitsNone]      BIT             NULL,
	[PetitionerUSVisitsStartDateVisit]             DATETIME2 (7)   NULL,
	[PetitionerUSVisitsEndDateVisit]             DATETIME2 (7)   NULL,
	[PetitionerRelativesChildInUSYes]      BIT             NULL,
	[PetitionerRelativesChildInUSNo]      BIT             NULL,
	[PetitionerRelativesFirstAndMiddleNames]              NVARCHAR (1000) NULL,
	[PetitionerRelativesLastName]              NVARCHAR (1000) NULL,
	[PetitionerRelativesSuffixAfterName]      INT NULL,
	[PetitionerRelativesStatus]      INT NULL,
	[PetitionerQuestion1ParamilitaryUnitYes]      BIT             NULL,
	[PetitionerQuestion1ParamilitaryUnitNo]      BIT             NULL,
	[PetitionerQuestion1ExplainQuestion]              NVARCHAR (1000) NULL,
	[PetitionerQuestion1HealthSignificanceYes]      BIT             NULL,
	[PetitionerQuestion1HealthSignificanceNo]      BIT             NULL,
	[PetitionerQuestion1SafetyOrWelfareYes]      BIT             NULL,
	[PetitionerQuestion1SafetyOrWelfareNo]      BIT             NULL,
	[PetitionerQuestion1DrugAbuserYes]      BIT             NULL,
	[PetitionerQuestion1DrugAbuserNo]      BIT             NULL,
	[PetitionerQuestion1NecessaryVaccinationsYes]      BIT             NULL,
	[PetitionerQuestion1NecessaryVaccinationsNo]      BIT             NULL,
	[PetitionerQuestion1ArrestedOffenseYes]      BIT             NULL,
	[PetitionerQuestion1ArrestedOffenseNo]      BIT             NULL,
	[PetitionerQuestion1ViolatedYes]      BIT             NULL,
	[PetitionerQuestion1ViolatedNo]      BIT             NULL,
	[PetitionerQuestion1EngageInProstitutionYes]      BIT             NULL,
	[PetitionerQuestion1EngageInProstitutionNo]      BIT             NULL,
	[PetitionerQuestion1MoneyLaunderingYes]      BIT             NULL,
	[PetitionerQuestion1MoneyLaunderingNo]      BIT             NULL,
	[PetitionerQuestion1HumanTraffickingOffenseYes]      BIT             NULL,
	[PetitionerQuestion1HumanTraffickingOffenseNo]      BIT             NULL,
	[PetitionerQuestion1KnowinglyAidedYes]      BIT             NULL,
	[PetitionerQuestion1KnowinglyAidedNo]      BIT             NULL,
	[PetitionerQuestion2KnowinglyAidedYes]      BIT             NULL,
	[PetitionerQuestion2KnowinglyAidedNo]      BIT             NULL,
	[PetitionerQuestion2ExplainQuestion]              NVARCHAR (1000) NULL,
	[PetitionerQuestion2TraffickingOffenseYes]      BIT             NULL,
	[PetitionerQuestion2TraffickingOffenseNo]      BIT             NULL,
	[PetitionerQuestion2IdentifiedPresidentYes]      BIT             NULL,
	[PetitionerQuestion2IdentifiedPresidentNo]      BIT             NULL,
	[PetitionerQuestion2ViolatedYes]      BIT             NULL,
	[PetitionerQuestion2ViolatedNo]      BIT             NULL,
	[PetitionerQuestion2EngageEspionageYes]      BIT             NULL,
	[PetitionerQuestion2EngageEspionageNo]      BIT             NULL,
	[PetitionerQuestion2TerroristActivitiesYes]      BIT             NULL,
	[PetitionerQuestion2TerroristActivitiesNo]      BIT             NULL,
	[PetitionerQuestion2FinancialAssistanceYes]      BIT             NULL,
	[PetitionerQuestion2FinancialAssistanceNo]      BIT             NULL,
	[PetitionerQuestion2TerroristOrganizationYes]      BIT             NULL,
	[PetitionerQuestion2TerroristOrganizationNo]      BIT             NULL,
	[PetitionerQuestion2GenocideYes]      BIT             NULL,
	[PetitionerQuestion2GenocideNo]      BIT             NULL,
	[PetitionerQuestion2TortureYes]      BIT             NULL,
	[PetitionerQuestion2TortureNo]      BIT             NULL,
	[PetitionerQuestion2IntentionallyAssistedYes]      BIT             NULL,
	[PetitionerQuestion2IntentionallyAssistedNo]      BIT             NULL,
	[PetitionerQuestion3JudicialKillingsYes]      BIT             NULL,
	[PetitionerQuestion3JudicialKillingsNo]      BIT             NULL,
	[PetitionerQuestion3ExplainQuestion]              NVARCHAR (1000) NULL,
	[PetitionerQuestion3EngagedRecruitmentYes]      BIT             NULL,
	[PetitionerQuestion3EngagedRecruitmentNo]      BIT             NULL,
	[PetitionerQuestion3ReligiousFreedomYes]      BIT             NULL,
	[PetitionerQuestion3ReligiousFreedomNo]      BIT             NULL,
	[PetitionerQuestion3TotalitarianPartyYes]      BIT             NULL,
	[PetitionerQuestion3TotalitarianPartyNo]      BIT             NULL,
	[PetitionerQuestion3IndirectlyAssistedYes]      BIT             NULL,
	[PetitionerQuestion3IndirectlyAssistedNo]      BIT             NULL,
	[PetitionerQuestion31ClaimOwnershipYes]      BIT             NULL,
	[PetitionerQuestion31ClaimOwnershipNo]      BIT             NULL,
	[PetitionerQuestion32ClaimOwnershipYes]      BIT             NULL,
	[PetitionerQuestion32ClaimOwnershipNo]      BIT             NULL,
	[PetitionerQuestion31ChemicalWeaponsYes]      BIT             NULL,
	[PetitionerQuestion31ChemicalWeaponsNo]      BIT             NULL,
	[PetitionerQuestion32ChemicalWeaponsYes]      BIT             NULL,
	[PetitionerQuestion32ChemicalWeaponsNo]      BIT             NULL,
	[PetitionerQuestion3EstablishmentYes]      BIT             NULL,
	[PetitionerQuestion3EstablishmentNo]      BIT             NULL,
	[PetitionerQuestion3ReimbursingSchoolYes]      BIT             NULL,
	[PetitionerQuestion3ReimbursingSchoolNo]      BIT             NULL,
	[PetitionerQuestion4BodilyTissueYes]      BIT             NULL,
	[PetitionerQuestion4BodilyTissueNo]      BIT             NULL,
	[PetitionerQuestion4ExplainQuestion]              NVARCHAR (1000) NULL,
	[PetitionerQuestion4INA274CYes]      BIT             NULL,
	[PetitionerQuestion4INA274CNo]      BIT             NULL,
	[PetitionerQuestion4RemovedUS5YearsYes]      BIT             NULL,
	[PetitionerQuestion4RemovedUS5YearsNo]      BIT             NULL,
	[PetitionerQuestion4RemovedUS20YearsYes]      BIT             NULL,
	[PetitionerQuestion4RemovedUS20YearsNo]      BIT             NULL,
	[PetitionerQuestion4RemovedUS10YearsYes]      BIT             NULL,
	[PetitionerQuestion4RemovedUS10YearsNo]      BIT             NULL,
	[PetitionerQuestion4ConvictedRemovedUSYes]      BIT             NULL,
	[PetitionerQuestion4ConvictedRemovedUSNo]      BIT             NULL,
	[PetitionerQuestion4Unlawfully180DaysYes]      BIT             NULL,
	[PetitionerQuestion4Unlawfully180DaysNo]      BIT             NULL,
	[PetitionerQuestion4Unlawfully1YearYes]      BIT             NULL,
	[PetitionerQuestion4Unlawfully1YearNo]      BIT             NULL,
	[PetitionerQuestion4WithheldCustodyYes]      BIT             NULL,
	[PetitionerQuestion4WithheldCustodyNo]      BIT             NULL,
	[PetitionerQuestion4ViolationLawYes]      BIT             NULL,
	[PetitionerQuestion4ViolationLawNo]      BIT             NULL,
	[PetitionerQuestion5AvoidingTaxationYes]      BIT             NULL,
	[PetitionerQuestion5AvoidingTaxationNo]      BIT             NULL,
	[PetitionerQuestion5ExplainQuestion]              NVARCHAR (1000) NULL,
	[PetitionerQuestion5FormerExchangeVisitorYes]      BIT             NULL,
	[PetitionerQuestion5FormerExchangeVisitorNo]      BIT             NULL,
	[PetitionerQuestion5SecretaryLaborYes]      BIT             NULL,
	[PetitionerQuestion5SecretaryLaborNo]      BIT             NULL,
	[PetitionerQuestion5ForeignMedicalSchoolYes]      BIT             NULL,
	[PetitionerQuestion5ForeignMedicalSchoolNo]      BIT             NULL,
	[PetitionerQuestion5HealthCareWorkerYes]      BIT             NULL,
	[PetitionerQuestion5HealthCareWorkerNo]      BIT             NULL,
	[PetitionerQuestion5PermanentlyIneligibleYes]      BIT             NULL,
	[PetitionerQuestion5PermanentlyIneligibleNo]      BIT             NULL,
	[PetitionerQuestion5EvadeMilitaryServiceYes]      BIT             NULL,
	[PetitionerQuestion5EvadeMilitaryServiceNo]      BIT             NULL,
	[PetitionerQuestion5PracticePolygamyYes]      BIT             NULL,
	[PetitionerQuestion5PracticePolygamyNo]      BIT             NULL,
	[PetitionerQuestion5SecretaryHomelandYes]      BIT             NULL,
	[PetitionerQuestion5SecretaryHomelandNo]      BIT             NULL,
	[PetitionerQuestion5ObtainVisaYes]      BIT             NULL,
	[PetitionerQuestion5ObtainVisaNo]      BIT             NULL,
    	[Deleted] BIT CONSTRAINT [DF_FormVisaSpouse_Deleted] DEFAULT ((0)) NOT NULL,
    	CONSTRAINT [PK_FormVisaSpouse] PRIMARY KEY CLUSTERED ([Id] ASC)
);
