CREATE TABLE [dbo].[FormTravelDocument] (
    [Id]			       BIGINT          IDENTITY (1, 1) NOT NULL,
    [AccountId] BIGINT NULL,
    [PersonalInformation01FullName]  NVARCHAR (1000) NULL,
    [PersonalInformation01GenderMale] BIT             NULL,
    [PersonalInformation01GenderFemale] BIT             NULL,
    [PersonalInformation01AnotherName]  NVARCHAR (1000) NULL,
    [PersonalInformation01DateOfBirth] DATETIME2 (7)   NULL,
    [PersonalInformation01BirthPlace]  NVARCHAR (1000) NULL,
    [PersonalInformation01CurrentNationality]  NVARCHAR (1000) NULL,
    [PersonalInformation01IDNumber]  NVARCHAR (1000) NULL,
    [PersonalInformation011IssueDate] DATETIME2 (7)   NULL,
    [PersonalInformation011PlaceOfIssue]  NVARCHAR (1000) NULL,
    [PersonalInformation01PassportNumber]  NVARCHAR (1000) NULL,
    [PersonalInformation012PlaceOfIssue]  NVARCHAR (1000) NULL,
    [PersonalInformation012IssueDate] DATETIME2 (7)   NULL,
    [PersonalInformation01ExpirationDate] DATETIME2 (7)   NULL,
    [PersonalInformation02OtherNationality]  NVARCHAR (1000) NULL,
    [PersonalInformation02PassportNumber]  NVARCHAR (1000) NULL,
    [PersonalInformation02Address]  NVARCHAR (1000) NULL,
    [PersonalInformation02CurrentAddress]  NVARCHAR (1000) NULL,
    [PersonalInformation02HomePhone]  NVARCHAR (1000) NULL,
    [PersonalInformation02CellPhone]  NVARCHAR (1000) NULL,
    [PersonalInformation02Email]  NVARCHAR (1000) NULL,
    [PersonalInformation02OtherPhoneEmailNo] BIT             NULL,
    [PersonalInformation02OtherPhoneEmailYes] BIT             NULL,
    [PersonalInformation02UseSocialMediaNo] BIT             NULL,
    [PersonalInformation02UseSocialMediaYes] BIT             NULL,
    [PersonalInformation02ListMoreSocialMedia]  NVARCHAR (1000) NULL,
    [PersonalInformation02UserNameSocialMedia]  NVARCHAR (1000) NULL,
    [PersonalInformation03MaritalStatusSingle] BIT             NULL,
    [PersonalInformation03MaritalStatusMarried] BIT             NULL,
    [PersonalInformation03MaritalStatusWidow] BIT             NULL,
    [PersonalInformation03MaritalStatusDivorce] BIT             NULL,
    [PersonalInformation03MaritalStatusSeparation] BIT             NULL,
    [PersonalInformation03NameOfHusbandWife]  NVARCHAR (1000) NULL,
    [PersonalInformation03DateOfBirth] DATETIME2 (7)   NULL,
    [PersonalInformation03BirthPlace]  NVARCHAR (1000) NULL,
    [PersonalInformation03Nationality]  NVARCHAR (1000) NULL,
    [PersonalInformation03Address]  NVARCHAR (1000) NULL,
    [PersonalInformation03MarriageRegistrationDate] DATETIME2 (7)   NULL,
    [PersonalInformation03DivorceProcedureDate] DATETIME2 (7)   NULL,
    [PersonalInformation03EverLostPassportNo] BIT             NULL,
    [PersonalInformation03EverLostPassportYes] BIT             NULL,
    [PersonalInformation03PassportNumber]  NVARCHAR (1000) NULL,
    [TripInformation04TripPurpose]  NVARCHAR (1000) NULL,
    [TripInformation04IntendedDateArrival] DATETIME2 (7)   NULL,
    [TripInformation04IntendedArrivalCity]  NVARCHAR (1000) NULL,
    [TripInformation04IntendedDateLeaving] DATETIME2 (7)   NULL,
    [TripInformation04IntendedLeavingCity]  NVARCHAR (1000) NULL,
    [TripInformation04PlacesToVisit]  NVARCHAR (1000) NULL,
    [TripInformation04WhereStayUS]  NVARCHAR (1000) NULL,
    [TripInformation04SponsorTripNo] BIT             NULL,
    [TripInformation04SponsorTripYes] BIT             NULL,
    [TripInformation04FullName]  NVARCHAR (1000) NULL,
    [TripInformation04Relationship]  NVARCHAR (1000) NULL,
    [TripInformation04Address]  NVARCHAR (1000) NULL,
    [TripInformation04PhoneNumber]  NVARCHAR (1000) NULL,
    [TripInformation05EverEnteredUSNo] BIT             NULL,
    [TripInformation05EverEnteredUSYes] BIT             NULL,
    [TripInformation05EverFingerprintedNo] BIT             NULL,
    [TripInformation05EverFingerprintedYes] BIT             NULL,
    [TripInformation051VisaType]  NVARCHAR (1000) NULL,
    [TripInformation051VisaNumber]  NVARCHAR (1000) NULL,
    [TripInformation051DateOfIssue] DATETIME2 (7)   NULL,
    [TripInformation051ExpirationDate] DATETIME2 (7)   NULL,
    [TripInformation051LengthStayFrom] DATETIME2 (7)   NULL,
    [TripInformation051LengthStayTo] DATETIME2 (7)   NULL,
    [TripInformation052VisaType]  NVARCHAR (1000) NULL,
    [TripInformation052VisaNumber]  NVARCHAR (1000) NULL,
    [TripInformation052DateOfIssue] DATETIME2 (7)   NULL,
    [TripInformation052ExpirationDate] DATETIME2 (7)   NULL,
    [TripInformation052LengthStayFrom] DATETIME2 (7)   NULL,
    [TripInformation052LengthStayTo] DATETIME2 (7)   NULL,
    [TripInformation053VisaType]  NVARCHAR (1000) NULL,
    [TripInformation053VisaNumber]  NVARCHAR (1000) NULL,
    [TripInformation053DateOfIssue] DATETIME2 (7)   NULL,
    [TripInformation053ExpirationDate] DATETIME2 (7)   NULL,
    [TripInformation053LengthStayFrom] DATETIME2 (7)   NULL,
    [TripInformation053LengthStayTo] DATETIME2 (7)   NULL,
    [TripInformation06EverRefusedVisaNo] BIT             NULL,
    [TripInformation06EverRefusedVisaYes] BIT             NULL,
    [TripInformation061Time]  NVARCHAR (1000) NULL,
    [TripInformation061Reason]  NVARCHAR (1000) NULL,
    [TripInformation06EverRefusedPermissionNo] BIT             NULL,
    [TripInformation06EverRefusedPermissionYes] BIT             NULL,
    [TripInformation062Time]  NVARCHAR (1000) NULL,
    [TripInformation062Reason]  NVARCHAR (1000) NULL,
    [TripInformation06CountriesVisited5Years]  NVARCHAR (1000) NULL,
    [TripInformation06LanguagesYouKnow]  NVARCHAR (1000) NULL,
    [UsContactInformation07FullName]  NVARCHAR (1000) NULL,
    [UsContactInformation07BelongsToOrganization]  NVARCHAR (1000) NULL,
    [UsContactInformation07Address]  NVARCHAR (1000) NULL,
    [UsContactInformation07PhoneNumber]  NVARCHAR (1000) NULL,
    [UsContactInformation07Email]  NVARCHAR (1000) NULL,
    [UsContactInformation07RelationshipApplicant]  NVARCHAR (1000) NULL,
    [FamilyInformation08FatherName]  NVARCHAR (1000) NULL,
    [FamilyInformation081DateOfBirth] DATETIME2 (7)   NULL,
    [FamilyInformation081CurrentAddress]  NVARCHAR (1000) NULL,
    [FamilyInformation08MotherName]  NVARCHAR (1000) NULL,
    [FamilyInformation082DateOfBirth] DATETIME2 (7)   NULL,
    [FamilyInformation082CurrentAddress]  NVARCHAR (1000) NULL,
    [FamilyInformation09BloodRelativesNo] BIT             NULL,
    [FamilyInformation09BloodRelativesYes] BIT             NULL,
    [FamilyInformation091FullName]  NVARCHAR (1000) NULL,
    [FamilyInformation091Relationship]  NVARCHAR (1000) NULL,
    [FamilyInformation091StatusCitizen] BIT             NULL,
    [FamilyInformation091StatusPermanentResident] BIT             NULL,
    [FamilyInformation091StatusNonimmigrant] BIT             NULL,
    [FamilyInformation091StatusOther] BIT             NULL,
    [FamilyInformation091OtherStatus]  NVARCHAR (1000) NULL,
    [FamilyInformation092FullName]  NVARCHAR (1000) NULL,
    [FamilyInformation092Relationship]  NVARCHAR (1000) NULL,
    [FamilyInformation092StatusCitizen] BIT             NULL,
    [FamilyInformation092StatusPermanentResident] BIT             NULL,
    [FamilyInformation092StatusNonimmigrant] BIT             NULL,
    [FamilyInformation092StatusOther] BIT             NULL,
    [FamilyInformation092OtherStatus]  NVARCHAR (1000) NULL,
    [FamilyInformation10OtherRelativesNo] BIT             NULL,
    [FamilyInformation10OtherRelativesYes] BIT             NULL,
    [FamilyInformation101FullName]  NVARCHAR (1000) NULL,
    [FamilyInformation101Relationship]  NVARCHAR (1000) NULL,
    [FamilyInformation101StatusCitizen] BIT             NULL,
    [FamilyInformation101StatusPermanentResident] BIT             NULL,
    [FamilyInformation101StatusNonimmigrant] BIT             NULL,
    [FamilyInformation101StatusOther] BIT             NULL,
    [FamilyInformation101OtherStatus]  NVARCHAR (1000) NULL,
    [FamilyInformation102FullName]  NVARCHAR (1000) NULL,
    [FamilyInformation102Relationship]  NVARCHAR (1000) NULL,
    [FamilyInformation102StatusCitizen] BIT             NULL,
    [FamilyInformation102StatusPermanentResident] BIT             NULL,
    [FamilyInformation102StatusNonimmigrant] BIT             NULL,
    [FamilyInformation102StatusOther] BIT             NULL,
    [FamilyInformation102OtherStatus]  NVARCHAR (1000) NULL,
    [JobInformation11WorkUnit]  NVARCHAR (1000) NULL,
    [JobInformation11Position]  NVARCHAR (1000) NULL,
    [JobInformation11FromDate] DATETIME2 (7)   NULL,
    [JobInformation11ToDate] DATETIME2 (7)   NULL,
    [JobInformation11JobDescription]  NVARCHAR (1000) NULL,
    [JobInformation11MonthlyIncome]  NVARCHAR (1000) NULL,
    [JobInformation11CompanyAddress]  NVARCHAR (1000) NULL,
    [JobInformation11CompanyPhone]  NVARCHAR (1000) NULL,
    [JobInformation11FullNameDdirector]  NVARCHAR (1000) NULL,
    [JobInformation12OtherJobNo] BIT             NULL,
    [JobInformation12OtherJobYes] BIT             NULL,
    [JobInformation12UnitOfWork]  NVARCHAR (1000) NULL,
    [JobInformation12Position]  NVARCHAR (1000) NULL,
    [JobInformation12FromDate] DATETIME2 (7)   NULL,
    [JobInformation12ToDate] DATETIME2 (7)   NULL,
    [JobInformation12JobDescription]  NVARCHAR (1000) NULL,
    [JobInformation12CompanyAddress]  NVARCHAR (1000) NULL,
    [JobInformation12CompanyPhone]  NVARCHAR (1000) NULL,
    [JobInformation12FullNameDirector]  NVARCHAR (1000) NULL,
    [JobInformation13School]  NVARCHAR (1000) NULL,
    [JobInformation13Address]  NVARCHAR (1000) NULL,
    [JobInformation13Courses]  NVARCHAR (1000) NULL,
    [JobInformation13FromDate]  DATETIME2 (7)   NULL,
    [JobInformation13ToDate]  DATETIME2 (7)   NULL,
    [Deleted]                          BIT             CONSTRAINT [DF_FormTravelDocument_Deleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_FormTravelDocument] PRIMARY KEY CLUSTERED ([Id] ASC)
);
