CREATE TABLE [dbo].[FormVisaParent] (
    	[Id] BIGINT IDENTITY (1, 1) NOT NULL,
    	[AccountId] BIGINT NULL,
	[PetitionerContactFirstName] NVARCHAR (1000) NULL,
	[PetitionerContactMiddleName] NVARCHAR (1000) NULL,
	[PetitionerContactLastName] NVARCHAR (1000) NULL,
	[PetitionerContactDaytimeTelephoneNumber] NVARCHAR (1000) NULL,
	[PetitionerContactEmailAddress] NVARCHAR (1000) NULL,
	[PetitionerContactDateOfBirth] DATETIME2 (7)   NULL,
	[PetitionerContactAlienRegistrationNumber] NVARCHAR (1000) NULL,
	[PetitionerContactCountryOfCitizenship] NVARCHAR (1000) NULL,
	[PetitionerContactMailingStreetAddressApt] BIT             NULL,
	[PetitionerContactMailingStreetAddressSte] BIT             NULL,
	[PetitionerContactMailingStreetAddressFlr] BIT             NULL,
	[PetitionerContactMailingStreetNumber] NVARCHAR (1000) NULL,
	[PetitionerContactCityOrTown] NVARCHAR (1000) NULL,
	[PetitionerContactState] NVARCHAR (1000) NULL,
	[PetitionerContactProvince] NVARCHAR (1000) NULL,
	[PetitionerContactZipCode] NVARCHAR (1000) NULL,
	[PetitionerContactCountry] NVARCHAR (1000) NULL,
	[PetitionerContactDifferentPhysicalYes] BIT             NULL,
	[PetitionerContactDifferentPhysicalNo] BIT             NULL,
	[PetitionerInformationEmployedAs] NVARCHAR (1000) NULL,
	[PetitionerInformationNameOfEmployer1] NVARCHAR (1000) NULL,
	[PetitionerInformationNameOfEmployer2] NVARCHAR (1000) NULL,
	[PetitionerInformationSelfEmployed] NVARCHAR (1000) NULL,
	[PetitionerInformationRetiredSince] DATETIME2 (7)   NULL,
	[PetitionerInformationUnemployedSince] DATETIME2 (7)   NULL,
	[PetitionerInformationAnnualIncomeIs] NVARCHAR (1000) NULL,
	[PetitionerInformationAnnualHouseholdIs] NVARCHAR (1000) NULL,
	[PetitionerInformationTaxYearMostRecent] NVARCHAR (1000) NULL,
	[PetitionerInformation2ndMostRecent] NVARCHAR (1000) NULL,
	[PetitionerInformation3rdMostRecent] NVARCHAR (1000) NULL,
	[PetitionerInformationIRSRequiredLevelYes] BIT             NULL,
	[PetitionerInformationIRSRequiredLevelNo] BIT             NULL,
	[PetitionertatusSocialSecurityNumber] NVARCHAR (1000) NULL,
	[PetitionertatusMaritalStatusUSCitizen] BIT             NULL,
	[PetitionertatusMaritalStatusUSNational] BIT             NULL,
	[PetitionertatusMaritalStatusGreenCard] BIT             NULL,
	[PetitionertatusAlienNumber] NVARCHAR (1000) NULL,
	[PetitionertatusCountryOfDomicile] NVARCHAR (1000) NULL,
	[PetitionertatusUSArmedForcesYes] BIT             NULL,
	[PetitionertatusUSArmedForcesNo] BIT             NULL,
	[PetitionertatusCurrentlyMarriedYes] BIT             NULL,
	[PetitionertatusCurrentlyMarriedNo] BIT             NULL,
	[PetitionertatusDependentChildrenYes] BIT             NULL,
	[PetitionertatusDependentChildrenNo] BIT             NULL,
	[PetitionertatusPreviouslyMarriedYes] BIT             NULL,
	[PetitionertatusPreviouslyMarriedNo] BIT             NULL,
	[PetitionerGenderPrincipalImmigrantMale] BIT             NULL,
	[PetitionerGenderPrincipalImmigrantFemale] BIT             NULL,
	[PetitionerGenderWithinSixMonthsImmigrantMale] BIT             NULL,
	[PetitionerGenderWithinSixMonthsImmigrantFemale] BIT             NULL,
	[PetitionerGenderMoreThanSixMonthsImmigrantMale] BIT             NULL,
	[PetitionerGenderMoreThanSixMonthsImmigrantFemale] BIT             NULL,
	[PetitionerAddressStreetApt] BIT             NULL,
	[PetitionerAddressStreetSte] BIT             NULL,
	[PetitionerAddressStreetFlr] BIT             NULL,
	[PetitionerAddressStreetNumber] NVARCHAR (1000) NULL,
	[PetitionerAddressCityOrTown] NVARCHAR (1000) NULL,
	[PetitionerAddressState] NVARCHAR (1000) NULL,
	[PetitionerAddressProvince] NVARCHAR (1000) NULL,
	[PetitionerAddressZipCode] NVARCHAR (1000) NULL,
	[PetitionerAddressCountry] NVARCHAR (1000) NULL,
	[PetitionerNameFirstName] NVARCHAR (1000) NULL,
	[PetitionerNameMiddleName] NVARCHAR (1000) NULL,
	[PetitionerNameLastName] NVARCHAR (1000) NULL,
	[PetitionerName1DaytimeTelephoneNumber] NVARCHAR (1000) NULL,
	[PetitionerName2DaytimeTelephoneNumber] NVARCHAR (1000) NULL,
	[PetitionerNameEmailAddress] NVARCHAR (1000) NULL,
	[PetitionerNameDateOfBirth] DATETIME2 (7)   NULL,
	[PetitionerNameAlienRegistrationNumber] NVARCHAR (1000) NULL,
	[PetitionerNameCountry] NVARCHAR (1000) NULL,
	[InterpreterNameFirstName] NVARCHAR (1000) NULL,
	[InterpreterNameLastName] NVARCHAR (1000) NULL,
	[InterpreterNameBusinessOrOrganization] NVARCHAR (1000) NULL,
	[InterpreterNameStreetApt] BIT             NULL,
	[InterpreterNameStreetSte] BIT             NULL,
	[InterpreterNameStreetFlr] BIT             NULL,
	[InterpreterNameStreetNumber] NVARCHAR (1000) NULL,
	[InterpreterNameCityOrTown] NVARCHAR (1000) NULL,
	[InterpreterNameProvince] NVARCHAR (1000) NULL,
	[InterpreterNameZipCode] NVARCHAR (1000) NULL,
	[InterpreterNameCountry] NVARCHAR (1000) NULL,
	[InterpreterNameDaytimeTelephoneNumber] NVARCHAR (1000) NULL,
	[InterpreterNameEmailAddress] NVARCHAR (1000) NULL,
	[Deleted] BIT CONSTRAINT [DF_FormVisaParent_Deleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_FormVisaParent] PRIMARY KEY CLUSTERED ([Id] ASC)
);
