CREATE TABLE [dbo].[FormTravelDocument] (
    [Id]			       BIGINT          IDENTITY (1, 1) NOT NULL,
    [AccountId] BIGINT NULL,
    [Personal01FullName]  NVARCHAR (1000) NULL,
    [Personal01GenderMale] BIT             NULL,
    [Personal01GenderFemale] BIT             NULL,
    [Personal01AnotherName]  NVARCHAR (1000) NULL,
    [Personal01DateOfBirth] DATETIME2 (7)   NULL,
    [Personal01BirthPlace]  NVARCHAR (1000) NULL,
    [Personal01BirthNationality]  NVARCHAR (1000) NULL,
    [Personal01CurrentNationality]  NVARCHAR (1000) NULL,
    [Personal01IDNumber]  NVARCHAR (1000) NULL,
    [Personal011IssueDate] DATETIME2 (7)   NULL,
    [Personal011PlaceOfIssue]  NVARCHAR (1000) NULL,
    [Personal01PassportNumber]  NVARCHAR (1000) NULL,
    [Personal012PlaceOfIssue]  NVARCHAR (1000) NULL,
    [Personal012IssueDate] DATETIME2 (7)   NULL,
    [Personal01ExpirationDate] DATETIME2 (7)   NULL,
    [Personal02OtherNationality]  NVARCHAR (1000) NULL,
    [Personal02PassportNumber]  NVARCHAR (1000) NULL,
    [Personal02Address]  NVARCHAR (1000) NULL,
    [Personal02CurrentAddress]  NVARCHAR (1000) NULL,
    [Personal02HomePhone]  NVARCHAR (1000) NULL,
    [Personal02CellPhone]  NVARCHAR (1000) NULL,
    [Personal02Email]  NVARCHAR (1000) NULL,
    [Personal02OtherPhoneEmailNo] BIT             NULL,
    [Personal02OtherPhoneEmailYes] BIT             NULL,
    [Personal02UseSocialMediaNo] BIT             NULL,
    [Personal02UseSocialMediaYes] BIT             NULL,
    [Personal02ListMoreSocialMedia]  NVARCHAR (1000) NULL,
    [Personal02UserNameSocialMedia]  NVARCHAR (1000) NULL,
    [Personal03MaritalStatusSingle] BIT             NULL,
    [Personal03MaritalStatusMarried] BIT             NULL,
    [Personal03MaritalStatusWidow] BIT             NULL,
    [Personal03MaritalStatusDivorce] BIT             NULL,
    [Personal03MaritalStatusSeparation] BIT             NULL,
    [Personal03NameOfHusbandWife]  NVARCHAR (1000) NULL,
    [Personal03DateOfBirth] DATETIME2 (7)   NULL,
    [Personal03BirthPlace]  NVARCHAR (1000) NULL,
    [Personal03Nationality]  NVARCHAR (1000) NULL,
    [Personal03Address]  NVARCHAR (1000) NULL,
    [Personal03MarriageRegistrationDate] DATETIME2 (7)   NULL,
    [Personal03DivorceProcedureDate] DATETIME2 (7)   NULL,
    [Personal03EverLostPassportNo] BIT             NULL,
    [Personal03EverLostPassportYes] BIT             NULL,
    [Personal03PassportNumber]  NVARCHAR (1000) NULL,
    [Trip04TripPurpose]  NVARCHAR (1000) NULL,
    [Trip04IntendedDateArrival] DATETIME2 (7)   NULL,
    [Trip04IntendedArrivalCity]  NVARCHAR (1000) NULL,
    [Trip04IntendedDateLeaving] DATETIME2 (7)   NULL,
    [Trip04IntendedLeavingCity]  NVARCHAR (1000) NULL,
    [Trip04PlacesToVisit]  NVARCHAR (1000) NULL,
    [Trip04WhereStayUS]  NVARCHAR (1000) NULL,
    [Trip04SponsorTripNo] BIT             NULL,
    [Trip04SponsorTripYes] BIT             NULL,
    [Trip04FullName]  NVARCHAR (1000) NULL,
    [Trip04Relationship]  NVARCHAR (1000) NULL,
    [Trip04Address]  NVARCHAR (1000) NULL,
    [Trip04PhoneNumber]  NVARCHAR (1000) NULL,
    [Trip05EverEnteredUSNo] BIT             NULL,
    [Trip05EverEnteredUSYes] BIT             NULL,
    [Trip05EverFingerprintedNo] BIT             NULL,
    [Trip05EverFingerprintedYes] BIT             NULL,
    [Trip051VisaType]  NVARCHAR (1000) NULL,
    [Trip051VisaNumber]  NVARCHAR (1000) NULL,
    [Trip051DateOfIssue] DATETIME2 (7)   NULL,
    [Trip051ExpirationDate] DATETIME2 (7)   NULL,
    [Trip051LengthStayFrom] DATETIME2 (7)   NULL,
    [Trip051LengthStayTo] DATETIME2 (7)   NULL,
    [Trip052VisaType]  NVARCHAR (1000) NULL,
    [Trip052VisaNumber]  NVARCHAR (1000) NULL,
    [Trip052DateOfIssue] DATETIME2 (7)   NULL,
    [Trip052ExpirationDate] DATETIME2 (7)   NULL,
    [Trip052LengthStayFrom] DATETIME2 (7)   NULL,
    [Trip052LengthStayTo] DATETIME2 (7)   NULL,
    [Trip053VisaType]  NVARCHAR (1000) NULL,
    [Trip053VisaNumber]  NVARCHAR (1000) NULL,
    [Trip053DateOfIssue] DATETIME2 (7)   NULL,
    [Trip053ExpirationDate] DATETIME2 (7)   NULL,
    [Trip053LengthStayFrom] DATETIME2 (7)   NULL,
    [Trip053LengthStayTo] DATETIME2 (7)   NULL,
    [Trip06EverRefusedVisaNo] BIT             NULL,
    [Trip06EverRefusedVisaYes] BIT             NULL,
    [Trip061Time]  NVARCHAR (1000) NULL,
    [Trip061Reason]  NVARCHAR (1000) NULL,
    [Trip06EverRefusedPermissionNo] BIT             NULL,
    [Trip06EverRefusedPermissionYes] BIT             NULL,
    [Trip062Time]  NVARCHAR (1000) NULL,
    [Trip062Reason]  NVARCHAR (1000) NULL,
    [Trip06CountriesVisited5Years]  NVARCHAR (1000) NULL,
    [Trip06LanguagesYouKnow]  NVARCHAR (1000) NULL,
    [UsContact07FullName]  NVARCHAR (1000) NULL,
    [UsContact07BelongsToOrganization]  NVARCHAR (1000) NULL,
    [UsContact07Address]  NVARCHAR (1000) NULL,
    [UsContact07PhoneNumber]  NVARCHAR (1000) NULL,
    [UsContact07Email]  NVARCHAR (1000) NULL,
    [UsContact07RelationshipApplicant]  NVARCHAR (1000) NULL,
    [Family08FatherName]  NVARCHAR (1000) NULL,
    [Family081DateOfBirth] DATETIME2 (7)   NULL,
    [Family081CurrentAddress]  NVARCHAR (1000) NULL,
    [Family08MotherName]  NVARCHAR (1000) NULL,
    [Family082DateOfBirth] DATETIME2 (7)   NULL,
    [Family082CurrentAddress]  NVARCHAR (1000) NULL,
    [Family09BloodRelativesNo] BIT             NULL,
    [Family09BloodRelativesYes] BIT             NULL,
    [Family091FullName]  NVARCHAR (1000) NULL,
    [Family091Relationship]  NVARCHAR (1000) NULL,
    [Family091StatusCitizen] BIT             NULL,
    [Family091StatusPermanentResident] BIT             NULL,
    [Family091StatusNonimmigrant] BIT             NULL,
    [Family091StatusOther] BIT             NULL,
    [Family091OtherStatus]  NVARCHAR (1000) NULL,
    [Family092FullName]  NVARCHAR (1000) NULL,
    [Family092Relationship]  NVARCHAR (1000) NULL,
    [Family092StatusCitizen] BIT             NULL,
    [Family092StatusPermanentResident] BIT             NULL,
    [Family092StatusNonimmigrant] BIT             NULL,
    [Family092StatusOther] BIT             NULL,
    [Family092OtherStatus]  NVARCHAR (1000) NULL,
    [Family10OtherRelativesNo] BIT             NULL,
    [Family10OtherRelativesYes] BIT             NULL,
    [Family101FullName]  NVARCHAR (1000) NULL,
    [Family101Relationship]  NVARCHAR (1000) NULL,
    [Family101StatusCitizen] BIT             NULL,
    [Family101StatusPermanentResident] BIT             NULL,
    [Family101StatusNonimmigrant] BIT             NULL,
    [Family101StatusOther] BIT             NULL,
    [Family101OtherStatus]  NVARCHAR (1000) NULL,
    [Family102FullName]  NVARCHAR (1000) NULL,
    [Family102Relationship]  NVARCHAR (1000) NULL,
    [Family102StatusCitizen] BIT             NULL,
    [Family102StatusPermanentResident] BIT             NULL,
    [Family102StatusNonimmigrant] BIT             NULL,
    [Family102StatusOther] BIT             NULL,
    [Family102OtherStatus]  NVARCHAR (1000) NULL,
    [Job11WorkUnit]  NVARCHAR (1000) NULL,
    [Job11Position]  NVARCHAR (1000) NULL,
    [Job11FromDate] DATETIME2 (7)   NULL,
    [Job11ToDate] DATETIME2 (7)   NULL,
    [Job11JobDescription]  NVARCHAR (1000) NULL,
    [Job11MonthlyIncome]  NVARCHAR (1000) NULL,
    [Job11CompanyAddress]  NVARCHAR (1000) NULL,
    [Job11CompanyPhone]  NVARCHAR (1000) NULL,
    [Job11FullNameDdirector]  NVARCHAR (1000) NULL,
    [Job12OtherJobNo] BIT             NULL,
    [Job12OtherJobYes] BIT             NULL,
    [Job12UnitOfWork]  NVARCHAR (1000) NULL,
    [Job12Position]  NVARCHAR (1000) NULL,
    [Job12FromDate] DATETIME2 (7)   NULL,
    [Job12ToDate] DATETIME2 (7)   NULL,
    [Job12JobDescription]  NVARCHAR (1000) NULL,
    [Job12CompanyAddress]  NVARCHAR (1000) NULL,
    [Job12CompanyPhone]  NVARCHAR (1000) NULL,
    [Job12FullNameDirector]  NVARCHAR (1000) NULL,
    [Job13School]  NVARCHAR (1000) NULL,
    [Job13Address]  NVARCHAR (1000) NULL,
    [Job13Courses]  NVARCHAR (1000) NULL,
    [Job13FromDate]  DATETIME2 (7)   NULL,
    [Job13ToDate]  DATETIME2 (7)   NULL,
    [Deleted]                          BIT             CONSTRAINT [DF_FormTravelDocument_Deleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_FormTravelDocument] PRIMARY KEY CLUSTERED ([Id] ASC)
);
