CREATE TABLE [dbo].[FormVisaParent] (
    	[Id] BIGINT IDENTITY (1, 1) NOT NULL,
    	[AccountId] BIGINT NULL,
	[PetitionerContactFirstName] NVARCHAR (1000) NULL,
	[PetitionerContactMiddleName] NVARCHAR (1000) NULL,
	[PetitionerContactLastName] NVARCHAR (1000) NULL,
	[PetitionerContactDaytimeTelephoneNumber] NVARCHAR (1000) NULL,
	[PetitionerContactEmailAddress] NVARCHAR (1000) NULL,
	[PetitionerContactDateOfBirth] DATETIME2 (7)   NULL,
	[PetitionerContactAlienRegistrationNumber] NVARCHAR (1000) NULL,
	[PetitionerContactCountryOfCitizenship] NVARCHAR (1000) NULL,
	[SponsorsContactMailingStreetAddressApt] BIT             NULL,
	[SponsorsContactMailingStreetAddressSte] BIT             NULL,
	[SponsorsContactMailingStreetAddressFlr] BIT             NULL,
	[SponsorsContactMailingStreetNumber] NVARCHAR (1000) NULL,
	[SponsorsContactCityOrTown] NVARCHAR (1000) NULL,
	[SponsorsContactState] NVARCHAR (1000) NULL,
	[SponsorsContactProvince] NVARCHAR (1000) NULL,
	[SponsorsContactZipCode] NVARCHAR (1000) NULL,
	[SponsorsContactCountry] NVARCHAR (1000) NULL,
	[SponsorsContactDifferentPhysicalYes] BIT             NULL,
	[SponsorsContactDifferentPhysicalNo] BIT             NULL,
	[SponsorInformationEmployedAs] NVARCHAR (1000) NULL,
	[SponsorInformationNameOfEmployer1] NVARCHAR (1000) NULL,
	[SponsorInformationNameOfEmployer2] NVARCHAR (1000) NULL,
	[SponsorInformationSelfEmployed] NVARCHAR (1000) NULL,
	[SponsorInformationRetiredSince] DATETIME2 (7)   NULL,
	[SponsorInformationUnemployedSince] DATETIME2 (7)   NULL,
	[SponsorInformationAnnualIncomeIs] NVARCHAR (1000) NULL,
	[SponsorInformationAnnualHouseholdIs] NVARCHAR (1000) NULL,
	[SponsorInformationTaxYearMostRecent] NVARCHAR (1000) NULL,
	[SponsorInformation2ndMostRecent] NVARCHAR (1000) NULL,
	[SponsorInformation3rdMostRecent] NVARCHAR (1000) NULL,
	[SponsorInformationIRSRequiredLevelYes] BIT             NULL,
	[SponsorInformationIRSRequiredLevelNo] BIT             NULL,
	[SponsorStatusSocialSecurityNumber] NVARCHAR (1000) NULL,
	[SponsorStatusMaritalStatusUSCitizen] BIT             NULL,
	[SponsorStatusMaritalStatusUSNational] BIT             NULL,
	[SponsorStatusMaritalStatusGreenCard] BIT             NULL,
	[SponsorStatusAlienNumber] NVARCHAR (1000) NULL,
	[SponsorStatusCountryOfDomicile] NVARCHAR (1000) NULL,
	[SponsorStatusUSArmedForcesYes] BIT             NULL,
	[SponsorStatusUSArmedForcesNo] BIT             NULL,
	[SponsorStatusCurrentlyMarriedYes] BIT             NULL,
	[SponsorStatusCurrentlyMarriedNo] BIT             NULL,
	[SponsorStatusDependentChildrenYes] BIT             NULL,
	[SponsorStatusDependentChildrenNo] BIT             NULL,
	[SponsorStatusPreviouslyMarriedYes] BIT             NULL,
	[SponsorStatusPreviouslyMarriedNo] BIT             NULL,
	[SponsorGenderPrincipalImmigrantMale] BIT             NULL,
	[SponsorGenderPrincipalImmigrantFemale] BIT             NULL,
	[SponsorGenderWithinSixMonthsImmigrantMale] BIT             NULL,
	[SponsorGenderWithinSixMonthsImmigrantFemale] BIT             NULL,
	[SponsorGenderMoreThanSixMonthsImmigrantMale] BIT             NULL,
	[SponsorGenderMoreThanSixMonthsImmigrantFemale] BIT             NULL,
	[SponsorAddressStreetApt] BIT             NULL,
	[SponsorAddressStreetSte] BIT             NULL,
	[SponsorAddressStreetFlr] BIT             NULL,
	[SponsorAddressStreetNumber] NVARCHAR (1000) NULL,
	[SponsorAddressCityOrTown] NVARCHAR (1000) NULL,
	[SponsorAddressState] NVARCHAR (1000) NULL,
	[SponsorAddressProvince] NVARCHAR (1000) NULL,
	[SponsorAddressZipCode] NVARCHAR (1000) NULL,
	[SponsorAddressCountry] NVARCHAR (1000) NULL,
	[SponsorNameFirstName] NVARCHAR (1000) NULL,
	[SponsorNameMiddleName] NVARCHAR (1000) NULL,
	[SponsorNameLastName] NVARCHAR (1000) NULL,
	[SponsorName1DaytimeTelephoneNumber] NVARCHAR (1000) NULL,
	[SponsorName2DaytimeTelephoneNumber] NVARCHAR (1000) NULL,
	[SponsorNameEmailAddress] NVARCHAR (1000) NULL,
	[SponsorNameDateOfBirth] DATETIME2 (7)   NULL,
	[SponsorNameAlienRegistrationNumber] NVARCHAR (1000) NULL,
	[SponsorNameCountry] NVARCHAR (1000) NULL,
	[InterpreterNameFirstName] NVARCHAR (1000) NULL,
	[InterpreterNameLastName] NVARCHAR (1000) NULL,
	[InterpreterNameBusinessOrOrganization] NVARCHAR (1000) NULL,
	[InterpreterNameStreetApt] BIT             NULL,
	[InterpreterNameStreetSte] BIT             NULL,
	[InterpreterNameStreetFlr] BIT             NULL,
	[InterpreterNameStreetNumber] NVARCHAR (1000) NULL,
	[InterpreterNameCityOrTown] NVARCHAR (1000) NULL,
	[InterpreterNameProvince] NVARCHAR (1000) NULL,
	[InterpreterNameZipCode] NVARCHAR (1000) NULL,
	[InterpreterNameCountry] NVARCHAR (1000) NULL,
	[InterpreterNameDaytimeTelephoneNumber] NVARCHAR (1000) NULL,
	[InterpreterNameEmailAddress] NVARCHAR (1000) NULL,
    	[Deleted] BIT CONSTRAINT [DF_FormVisaParent_Deleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_FormVisaParent] PRIMARY KEY CLUSTERED ([Id] ASC)
);
