

CREATE TABLE [dbo].[FormVisaFiance] (
    	[Id] BIGINT IDENTITY (1, 1) NOT NULL,
    	[AccountId] BIGINT NULL,    	
        [Beneficiary1FullName]  NVARCHAR (1000) NULL,
        [Beneficiary1PlaceOfBirth]  NVARCHAR (1000) NULL,
        [Beneficiary1HasBeenUSYes]  BIT NULL,
        [Beneficiary1HasBeenUSNo]  BIT NULL,
        [Beneficiary1NamesUsed]  NVARCHAR (1000) NULL,
        [Beneficiary1GreenCardNumber]  NVARCHAR (1000) NULL,
        [Beneficiary1SocialSecurityNumber]  NVARCHAR (1000) NULL,
        [Beneficiary1ConsularOfficeWishes]  NVARCHAR (1000) NULL,
        [Beneficiary1PrimaryLanguage]  NVARCHAR (1000) NULL,
        [Beneficiary1HomePhoneNumber]  NVARCHAR (1000) NULL,
        [Beneficiary1Mobile]  NVARCHAR (1000) NULL,
        [Beneficiary1OfficeTelephone]  NVARCHAR (1000) NULL,
        [Beneficiary1FaxNumber]  NVARCHAR (1000) NULL,
        [Beneficiary1EmailAddress]  NVARCHAR (1000) NULL,
        [Beneficiary1FatherName]  NVARCHAR (1000) NULL,
        [Beneficiary1FatherDateOfBirth]   DATETIME2 (7)   NULL,
        [Beneficiary1FatherPlaceOfBirth]  NVARCHAR (1000) NULL,
        [Beneficiary1FatherCityCountryResidence]  NVARCHAR (1000) NULL,
        [Beneficiary1MotherName]  NVARCHAR (1000) NULL,
        [Beneficiary1MotherDateOfBirth]   DATETIME2 (7)   NULL,
        [Beneficiary1MotherPlaceOfBirth]  NVARCHAR (1000) NULL,
        [Beneficiary1MotherCityCountryResidence]  NVARCHAR (1000) NULL,
        [Beneficiary11NameOfExSpouse]  NVARCHAR (1000) NULL,
        [Beneficiary11BirthDateOfExSpouse]   DATETIME2 (7)   NULL,
        [Beneficiary11BirthPlaceOfExSpouse]  NVARCHAR (1000) NULL,
        [Beneficiary11DateOfMarriage]   DATETIME2 (7)   NULL,
        [Beneficiary11PlaceOfMarriage]  NVARCHAR (1000) NULL,
        [Beneficiary12NameOfExSpouse]  NVARCHAR (1000) NULL,
        [Beneficiary12BirthDateOfExSpouse]   DATETIME2 (7)   NULL,
        [Beneficiary12BirthPlaceOfExSpouse]  NVARCHAR (1000) NULL,
        [Beneficiary12DateOfMarriage]   DATETIME2 (7)   NULL,
        [Beneficiary12PlaceOfMarriage]  NVARCHAR (1000) NULL,
        [Beneficiary13NameOfExSpouse]  NVARCHAR (1000) NULL,
        [Beneficiary13BirthDateOfExSpouse]   DATETIME2 (7)   NULL,
        [Beneficiary13BirthPlaceOfExSpouse]  NVARCHAR (1000) NULL,
        [Beneficiary13DateOfMarriage]   DATETIME2 (7)   NULL,
        [Beneficiary13PlaceOfMarriage]  NVARCHAR (1000) NULL,
        [Beneficiary14NameOfExSpouse]  NVARCHAR (1000) NULL,
        [Beneficiary14BirthDateOfExSpouse]   DATETIME2 (7)   NULL,
        [Beneficiary14BirthPlaceOfExSpouse]  NVARCHAR (1000) NULL,
        [Beneficiary14DateOfMarriage]   DATETIME2 (7)   NULL,
        [Beneficiary14PlaceOfMarriage]  NVARCHAR (1000) NULL,
        [Beneficiary21CurrentHouseStreet]  NVARCHAR (1000) NULL,
        [Beneficiary21City]  NVARCHAR (1000) NULL,
        [Beneficiary21StateCounty]  NVARCHAR (1000) NULL,
        [Beneficiary21ZipCode]  NVARCHAR (1000) NULL,
        [Beneficiary21FromMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary21ToMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary22CurrentHouseStreet]  NVARCHAR (1000) NULL,
        [Beneficiary22City]  NVARCHAR (1000) NULL,
        [Beneficiary22StateCounty]  NVARCHAR (1000) NULL,
        [Beneficiary22ZipCode]  NVARCHAR (1000) NULL,
        [Beneficiary22FromMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary22ToMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary23CurrentHouseStreet]  NVARCHAR (1000) NULL,
        [Beneficiary23City]  NVARCHAR (1000) NULL,
        [Beneficiary23StateCounty]  NVARCHAR (1000) NULL,
        [Beneficiary23ZipCode]  NVARCHAR (1000) NULL,
        [Beneficiary23FromMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary23ToMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary24CurrentHouseStreet]  NVARCHAR (1000) NULL,
        [Beneficiary24City]  NVARCHAR (1000) NULL,
        [Beneficiary24StateCounty]  NVARCHAR (1000) NULL,
        [Beneficiary24ZipCode]  NVARCHAR (1000) NULL,
        [Beneficiary24FromMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary24ToMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary25CurrentHouseStreet]  NVARCHAR (1000) NULL,
        [Beneficiary25City]  NVARCHAR (1000) NULL,
        [Beneficiary25StateCounty]  NVARCHAR (1000) NULL,
        [Beneficiary25ZipCode]  NVARCHAR (1000) NULL,
        [Beneficiary25FromMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary25ToMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary3HouseStreetName]  NVARCHAR (1000) NULL,
        [Beneficiary3City]  NVARCHAR (1000) NULL,
        [Beneficiary3StateCounty]  NVARCHAR (1000) NULL,
        [Beneficiary3ZipCode]  NVARCHAR (1000) NULL,
        [Beneficiary3FromMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary3ToMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary41NameWorkplaceAddress]  NVARCHAR (1000) NULL,
        [Beneficiary41Position]  NVARCHAR (1000) NULL,
        [Beneficiary41FromMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary41ToMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary42NameWorkplaceAddress]  NVARCHAR (1000) NULL,
        [Beneficiary42Position]  NVARCHAR (1000) NULL,
        [Beneficiary42FromMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary42ToMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary43NameWorkplaceAddress]  NVARCHAR (1000) NULL,
        [Beneficiary43Position]  NVARCHAR (1000) NULL,
        [Beneficiary43FromMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary43ToMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary44NameWorkplaceAddress]  NVARCHAR (1000) NULL,
        [Beneficiary44Position]  NVARCHAR (1000) NULL,
        [Beneficiary44FromMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary44ToMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary45NameWorkplaceAddress]  NVARCHAR (1000) NULL,
        [Beneficiary45Position]  NVARCHAR (1000) NULL,
        [Beneficiary45FromMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary45ToMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary5NameAddressWork]  NVARCHAR (1000) NULL,
        [Beneficiary5Position]  NVARCHAR (1000) NULL,
        [Beneficiary5FromMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary5ToMonthYear]  NVARCHAR (1000) NULL,
        [Beneficiary5AllPreviousVisaRefusals]  NVARCHAR (1000) NULL,
        [Beneficiary5HasAppliedWorkPermitYes]  BIT NULL,
        [Beneficiary5HasAppliedWorkPermitNo]  BIT NULL,
        [Beneficiary5WhenAndWhere]  NVARCHAR (1000) NULL,
        [Beneficiary5ApprovedYes]  BIT NULL,
        [Beneficiary5ApprovedNo]  BIT NULL,
        [Beneficiary5NamesOrganizationsMember]  NVARCHAR (1000) NULL,
        [Beneficiary5DescribePeopleMet]  NVARCHAR (1000) NULL,
        [Beneficiary5CanMatchmakingYes]  BIT NULL,
        [Beneficiary5CanMatchmakingNo]  BIT NULL,
        [Beneficiary5HaveEverViolatedYes]  BIT NULL,
        [Beneficiary5HaveEverViolatedNo]  BIT NULL,
        [Beneficiary5ViolatedProvideDetails]  NVARCHAR (1000) NULL,
        [Beneficiary5HasEverSufferedYes]  BIT NULL,
        [Beneficiary5HasEverSufferedNo]  BIT NULL,
        [Beneficiary5SufferedProvideDetails]  NVARCHAR (1000) NULL,
        [Beneficiary5HasInMilitaryYes]  BIT NULL,
        [Beneficiary5HasInMilitaryNo]  BIT NULL,
        [Beneficiary5NameOfOrganization]  NVARCHAR (1000) NULL,
        [Beneficiary5EnlistmentDate]   DATETIME2 (7)   NULL,
        [Beneficiary5WhereToEnlist]  NVARCHAR (1000) NULL,
        [Sponsor1Name]  NVARCHAR (1000) NULL,
        [Sponsor1BirthPlace]  NVARCHAR (1000) NULL,
        [Sponsor1IsFianceYes]  BIT NULL,
        [Sponsor1IsFianceNo]  BIT NULL,
        [Sponsor1NamesUsed]  NVARCHAR (1000) NULL,
        [Sponsor1GreenCardNumber]  NVARCHAR (1000) NULL,
        [Sponsor1SocialSecurityNumber]  NVARCHAR (1000) NULL,
        [Sponsor1HomePhoneNumber]  NVARCHAR (1000) NULL,
        [Sponsor1Mobile]  NVARCHAR (1000) NULL,
        [Sponsor1OfficePhone]  NVARCHAR (1000) NULL,
        [Sponsor1FaxNumber]  NVARCHAR (1000) NULL,
        [Sponsor1EmailAddress]  NVARCHAR (1000) NULL,
        [Sponsor1FatherName]  NVARCHAR (1000) NULL,
        [Sponsor1FatherBirthDate]   DATETIME2 (7)   NULL,
        [Sponsor1FatherBirthPlace]  NVARCHAR (1000) NULL,
        [Sponsor1FatherCityCountry]  NVARCHAR (1000) NULL,
        [Sponsor1MotherName]  NVARCHAR (1000) NULL,
        [Sponsor1MotherBirthDate]   DATETIME2 (7)   NULL,
        [Sponsor1MotherBirthPlace]  NVARCHAR (1000) NULL,
        [Sponsor1MotherCityCountry]  NVARCHAR (1000) NULL,
        [Sponsor11NameExSpouse]  NVARCHAR (1000) NULL,
        [Sponsor11BirthDateExSpouse]   DATETIME2 (7)   NULL,
        [Sponsor11BirthplaceExSpouse]  NVARCHAR (1000) NULL,
        [Sponsor11MarriageDate]   DATETIME2 (7)   NULL,
        [Sponsor11MarriagePlace]  NVARCHAR (1000) NULL,
        [Sponsor12NameExSpouse]  NVARCHAR (1000) NULL,
        [Sponsor12BirthDateExSpouse]   DATETIME2 (7)   NULL,
        [Sponsor12BirthPlaceExSpouse]  NVARCHAR (1000) NULL,
        [Sponsor12MarriageDate]   DATETIME2 (7)   NULL,
        [Sponsor12MarriagePlace]  NVARCHAR (1000) NULL,
        [Sponsor13NameExSpouse]  NVARCHAR (1000) NULL,
        [Sponsor13BirthDateExSpouse]   DATETIME2 (7)   NULL,
        [Sponsor13BirthPlaceExSpouse]  NVARCHAR (1000) NULL,
        [Sponsor13MarriageDate]   DATETIME2 (7)   NULL,
        [Sponsor13MarriagePlace]  NVARCHAR (1000) NULL,
        [Sponsor21CurrentHouseStreet]  NVARCHAR (1000) NULL,
        [Sponsor21City]  NVARCHAR (1000) NULL,
        [Sponsor21StateCounty]  NVARCHAR (1000) NULL,
        [Sponsor21ZipCode]  NVARCHAR (1000) NULL,
        [Sponsor21FromMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor21ToMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor22CurrentHouseStreet]  NVARCHAR (1000) NULL,
        [Sponsor22City]  NVARCHAR (1000) NULL,
        [Sponsor22StateCounty]  NVARCHAR (1000) NULL,
        [Sponsor22ZipCode]  NVARCHAR (1000) NULL,
        [Sponsor22FromMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor22ToMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor23CurrentHouseStreet]  NVARCHAR (1000) NULL,
        [Sponsor23City]  NVARCHAR (1000) NULL,
        [Sponsor23StateCounty]  NVARCHAR (1000) NULL,
        [Sponsor23ZipCode]  NVARCHAR (1000) NULL,
        [Sponsor23FromMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor23ToMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor24CurrentHouseStreet]  NVARCHAR (1000) NULL,
        [Sponsor24City]  NVARCHAR (1000) NULL,
        [Sponsor24StateCounty]  NVARCHAR (1000) NULL,
        [Sponsor24ZipCode]  NVARCHAR (1000) NULL,
        [Sponsor24FromMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor24ToMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor25CurrentHouseStreet]  NVARCHAR (1000) NULL,
        [Sponsor25City]  NVARCHAR (1000) NULL,
        [Sponsor25StateCounty]  NVARCHAR (1000) NULL,
        [Sponsor25ZipCode]  NVARCHAR (1000) NULL,
        [Sponsor25FromMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor25ToMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor3HouseStreetName]  NVARCHAR (1000) NULL,
        [Sponsor3City]  NVARCHAR (1000) NULL,
        [Sponsor3StateCounty]  NVARCHAR (1000) NULL,
        [Sponsor3ZipCode]  NVARCHAR (1000) NULL,
        [Sponsor3FromMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor3ToMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor41NameWorkplaceAddress]  NVARCHAR (1000) NULL,
        [Sponsor41Position]  NVARCHAR (1000) NULL,
        [Sponsor41FromMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor41ToMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor42NameWorkplaceAddress]  NVARCHAR (1000) NULL,
        [Sponsor42Position]  NVARCHAR (1000) NULL,
        [Sponsor42FromMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor42ToMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor43NameWorkplaceAddress]  NVARCHAR (1000) NULL,
        [Sponsor43Position]  NVARCHAR (1000) NULL,
        [Sponsor43FromMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor43ToMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor44NameWorkplaceAddress]  NVARCHAR (1000) NULL,
        [Sponsor44Position]  NVARCHAR (1000) NULL,
        [Sponsor44FromMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor44ToMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor45NameWorkplaceAddress]  NVARCHAR (1000) NULL,
        [Sponsor45Position]  NVARCHAR (1000) NULL,
        [Sponsor45FromMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor45ToMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor5NameAddressWork]  NVARCHAR (1000) NULL,
        [Sponsor5Position]  NVARCHAR (1000) NULL,
        [Sponsor5FromMonthYear]  NVARCHAR (1000) NULL,
        [Sponsor5ToMonthYear]  NVARCHAR (1000) NULL,
        [BeneficiaryProfileFormI94]  BIT NULL,
        [BeneficiaryProfileBirthCertificate]  BIT NULL,
        [BeneficiaryProfileI20Documents]  BIT NULL,
        [BeneficiaryProfileCriminalRecord]  BIT NULL,
        [BeneficiaryProfilePassportPhotos]  BIT NULL,
        [BeneficiaryProfilePreviousDivorce]  BIT NULL,
        [BeneficiaryProfilePapersRelated]  BIT NULL,
        [SponsorProfileLetterConfirmation]  BIT NULL,
        [SponsorProfileBankStatement]  BIT NULL,
        [SponsorProfileTaxReturns]  BIT NULL,
        [SponsorProfileW2PaystubsChecks]  BIT NULL,
        [SponsorProfileDocumentsShowing]  BIT NULL,
        [SponsorProfilePassportPhotos]  BIT NULL,
        [SponsorProfilePreviousDivorce]  BIT NULL,	  
    	[Deleted] BIT CONSTRAINT [DF_FormVisaFiance_Deleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_FormVisaFiance] PRIMARY KEY CLUSTERED ([Id] ASC)
);
